{{ config(materialized='table', tags=['inventory', 'domain:serving_ai', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/serving_ai/compute_ai_gateway_usage.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT
  CAST(g.event_time AS DATE)           AS usage_date,
  g.workspace_id                       AS workspace_id,
  g.endpoint_name AS endpoint_name,
  {{ mask_user('g.requester') }}                                  AS requester,
  COUNT(*)                                                                          AS total_requests,
  -- 2xx == success; 429 == rate-limit/quota; other == error (unconfirmed mapping, see caveats).
  SUM(CASE WHEN g.status_code BETWEEN 200 AND 299 THEN 1 ELSE 0 END)                AS success_requests,
  SUM(CASE WHEN g.status_code = 429 THEN 1 ELSE 0 END)                              AS rate_limited_requests,
  SUM(CASE WHEN g.status_code IS NOT NULL
            AND NOT (g.status_code BETWEEN 200 AND 299)
            AND g.status_code <> 429 THEN 1 ELSE 0 END)                            AS error_requests,
  -- Token throughput is its own magnitude, never blended with request counts.
  SUM(COALESCE(g.input_tokens, 0))                                                  AS input_tokens,
  SUM(COALESCE(g.output_tokens, 0))                                                 AS output_tokens,
  -- Latency via percentile (exact) -- percentile_approx differs between the two build paths.
  quantile_cont(g.latency_ms, 0.5)                                                    AS p50_latency_ms,
  quantile_cont(g.latency_ms, 0.95)                                                   AS p95_latency_ms,
  MAX(g.latency_ms)                                                                AS max_latency_ms
FROM {{ source('system_ai_gateway', 'usage') }} g
WHERE g.event_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND g.event_time <  {{ audit_today() }}
GROUP BY
  CAST(g.event_time AS DATE),
  g.workspace_id,
  g.endpoint_name,
  g.requester
ORDER BY usage_date DESC, total_requests DESC
{%- else %}
SELECT
  CAST(g.event_time AS DATE)           AS usage_date,
  g.workspace_id                       AS workspace_id,
  g.endpoint_name AS endpoint_name,
  {{ mask_user('g.requester') }}                                  AS requester,
  COUNT(*)                                                                          AS total_requests,
  -- 2xx == success; 429 == rate-limit/quota; other == error (unconfirmed mapping, see caveats).
  SUM(CASE WHEN g.status_code BETWEEN 200 AND 299 THEN 1 ELSE 0 END)                AS success_requests,
  SUM(CASE WHEN g.status_code = 429 THEN 1 ELSE 0 END)                              AS rate_limited_requests,
  SUM(CASE WHEN g.status_code IS NOT NULL
            AND NOT (g.status_code BETWEEN 200 AND 299)
            AND g.status_code <> 429 THEN 1 ELSE 0 END)                            AS error_requests,
  -- Token throughput is its own magnitude, never blended with request counts.
  SUM(COALESCE(g.input_tokens, 0))                                                  AS input_tokens,
  SUM(COALESCE(g.output_tokens, 0))                                                 AS output_tokens,
  -- Latency via percentile (exact) -- percentile_approx differs between the two build paths.
  percentile(g.latency_ms, 0.5)                                                    AS p50_latency_ms,
  percentile(g.latency_ms, 0.95)                                                   AS p95_latency_ms,
  MAX(g.latency_ms)                                                                AS max_latency_ms
FROM {{ source('system_ai_gateway', 'usage') }} g
WHERE g.event_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND g.event_time <  {{ audit_today() }}
GROUP BY
  CAST(g.event_time AS DATE),
  g.workspace_id,
  g.endpoint_name,
  g.requester
ORDER BY usage_date DESC, total_requests DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
