{{ config(materialized='table', tags=['finding', 'domain:storage', 'tier:deep']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/storage/po_data_skipping_backfill.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT workspace_id, catalog_name, schema_name, table_id, table_name,
       operation_metrics['added_data_skipping_columns']   AS added_data_skipping_columns,
       operation_metrics['removed_data_skipping_columns'] AS removed_data_skipping_columns,
       operation_metrics['new_data_skipping_columns']     AS new_data_skipping_columns,
       SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) AS scanned_bytes,
       SUM(CAST(operation_metrics['number_of_scanned_files'] AS BIGINT)) AS scanned_files,
       MAX(end_time) AS last_event_time,
       -- status: worst-first band on scan cost with zero ADDED-column gain (field heuristic; {{ param('po_data_skipping_backfill', 'warn_scan_gb', 100) }} / {{ param('po_data_skipping_backfill', 'crit_scan_gb', 500) }}).
       -- new_data_skipping_columns is not a reliable gain signal (real events don't populate it) - see caveats.
       CASE
         WHEN SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) IS NULL THEN 'NOT_ASSESSED'
         WHEN operation_metrics['added_data_skipping_columns'] IS NULL
              AND operation_metrics['removed_data_skipping_columns'] IS NULL
              AND operation_metrics['new_data_skipping_columns'] IS NULL THEN 'NOT_ASSESSED'
         WHEN (operation_metrics['added_data_skipping_columns'] IS NULL OR operation_metrics['added_data_skipping_columns'] = '')
              AND SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) >= {{ param('po_data_skipping_backfill', 'crit_scan_gb', 500) }} * 1e9 THEN 'CRITICAL'
         WHEN (operation_metrics['added_data_skipping_columns'] IS NULL OR operation_metrics['added_data_skipping_columns'] = '')
              AND SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) >= {{ param('po_data_skipping_backfill', 'warn_scan_gb', 100) }} * 1e9 THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_storage', 'predictive_optimization_operations_history') }}
WHERE operation_type = 'DATA_SKIPPING_COLUMN_SELECTION'
  AND start_time >= {{ audit_today() }} - (({{ w }}) * INTERVAL 1 DAY) AND start_time < {{ audit_today() }}
GROUP BY workspace_id, catalog_name, schema_name, table_id, table_name,
         operation_metrics['added_data_skipping_columns'], operation_metrics['removed_data_skipping_columns'],
         operation_metrics['new_data_skipping_columns']
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'OK' THEN 2 ELSE 3 END, scanned_bytes DESC
{%- else %}
SELECT workspace_id, catalog_name, schema_name, table_id, table_name,
       operation_metrics['added_data_skipping_columns']   AS added_data_skipping_columns,
       operation_metrics['removed_data_skipping_columns'] AS removed_data_skipping_columns,
       operation_metrics['new_data_skipping_columns']     AS new_data_skipping_columns,
       SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) AS scanned_bytes,
       SUM(CAST(operation_metrics['number_of_scanned_files'] AS BIGINT)) AS scanned_files,
       MAX(end_time) AS last_event_time,
       -- status: worst-first band on scan cost with zero ADDED-column gain (field heuristic; {{ param('po_data_skipping_backfill', 'warn_scan_gb', 100) }} / {{ param('po_data_skipping_backfill', 'crit_scan_gb', 500) }}).
       -- new_data_skipping_columns is not a reliable gain signal (real events don't populate it) - see caveats.
       CASE
         WHEN SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) IS NULL THEN 'NOT_ASSESSED'
         WHEN operation_metrics['added_data_skipping_columns'] IS NULL
              AND operation_metrics['removed_data_skipping_columns'] IS NULL
              AND operation_metrics['new_data_skipping_columns'] IS NULL THEN 'NOT_ASSESSED'
         WHEN (operation_metrics['added_data_skipping_columns'] IS NULL OR operation_metrics['added_data_skipping_columns'] = '')
              AND SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) >= {{ param('po_data_skipping_backfill', 'crit_scan_gb', 500) }} * 1e9 THEN 'CRITICAL'
         WHEN (operation_metrics['added_data_skipping_columns'] IS NULL OR operation_metrics['added_data_skipping_columns'] = '')
              AND SUM(CAST(operation_metrics['amount_of_scanned_bytes'] AS BIGINT)) >= {{ param('po_data_skipping_backfill', 'warn_scan_gb', 100) }} * 1e9 THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_storage', 'predictive_optimization_operations_history') }}
WHERE operation_type = 'DATA_SKIPPING_COLUMN_SELECTION'
  AND start_time >= {{ audit_today() }} - INTERVAL {{ w }} DAYS AND start_time < {{ audit_today() }}
GROUP BY workspace_id, catalog_name, schema_name, table_id, table_name,
         operation_metrics['added_data_skipping_columns'], operation_metrics['removed_data_skipping_columns'],
         operation_metrics['new_data_skipping_columns']
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'OK' THEN 2 ELSE 3 END, scanned_bytes DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
