{{ config(materialized='table', tags=['inventory', 'domain:storage', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/storage/storage_target_table_discovery.sql (app-owned). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT
    table_catalog || '.' || table_schema || '.' || table_name AS target_table,
    table_catalog,
    table_schema,
    table_name,
    table_type,
    data_source_format
FROM {{ source('system_information_schema', 'tables') }}
WHERE table_type <> 'VIEW'
ORDER BY table_catalog, table_schema, table_name
{%- else %}
SELECT
    table_catalog || '.' || table_schema || '.' || table_name AS target_table,
    table_catalog,
    table_schema,
    table_name,
    table_type,
    data_source_format
FROM {{ source('system_information_schema', 'tables') }}
WHERE table_type <> 'VIEW'
ORDER BY table_catalog, table_schema, table_name
{%- endif %}
) q
