{{ config(materialized='table', tags=['inventory', 'domain:storage', 'tier:deep']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/storage/table_inventory_type.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT table_catalog, table_schema, table_type, data_source_format,
       COUNT(*) AS table_count
FROM {{ source('system_information_schema', 'tables') }}
GROUP BY table_catalog, table_schema, table_type, data_source_format
ORDER BY table_catalog, table_schema, table_type
{%- else %}
SELECT table_catalog, table_schema, table_type, data_source_format,
       COUNT(*) AS table_count
FROM {{ source('system_information_schema', 'tables') }}
GROUP BY table_catalog, table_schema, table_type, data_source_format
ORDER BY table_catalog, table_schema, table_type
{%- endif %}
) q
