{{ config(materialized='table', tags=['inventory', 'domain:jobs_pipelines', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/jobs_pipelines/lakeflow_termination_type_probe.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT workspace_id, job_id, termination_type, COUNT(*) AS run_rows
FROM {{ source('system_lakeflow', 'job_run_timeline') }}
WHERE period_start_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND result_state IS NOT NULL
GROUP BY workspace_id, job_id, termination_type
ORDER BY workspace_id, run_rows DESC
{%- else %}
SELECT workspace_id, job_id, termination_type, COUNT(*) AS run_rows
FROM {{ source('system_lakeflow', 'job_run_timeline') }}
WHERE period_start_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND result_state IS NOT NULL
GROUP BY workspace_id, job_id, termination_type
ORDER BY workspace_id, run_rows DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
