{{ config(materialized='table', tags=['finding', 'domain:jobs_pipelines', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/jobs_pipelines/lakeflow_stale_zombie_jobs.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH latest_jobs AS (
  SELECT workspace_id, job_id, name, run_as, creator_id, create_time, delete_time
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
),
last_run AS (
  SELECT workspace_id, job_id, MAX(period_start_time) AS last_run_start
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  GROUP BY workspace_id, job_id
),
capture_floor AS (
  -- how far back this WORKSPACE's own job_run_timeline history reaches, unfiltered by job
  SELECT workspace_id,
         date_diff('day', MIN(period_start_time), {{ audit_today() }}) AS capture_floor_days
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  GROUP BY workspace_id
),
price AS (
  SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate
  FROM {{ list_prices() }} list_prices
),
cost_rollup AS (
  SELECT u.workspace_id,
         u.usage_metadata.job_id AS job_id,
         SUM(u.usage_quantity)                            AS net_dbus,
         SUM(u.usage_quantity * COALESCE(p.list_rate, 0)) AS est_usd_list,
         CASE
           WHEN SUM(CASE WHEN p.list_rate IS NULL AND upper(u.sku_name) NOT LIKE '%FREE_USAGE%'
                         THEN u.usage_quantity ELSE 0 END) > 0 THEN 'unpriced'
           WHEN SUM(CASE WHEN p.list_rate IS NOT NULL THEN u.usage_quantity ELSE 0 END) = 0 THEN 'free'
           ELSE 'priced'
         END                                               AS price_basis
  FROM {{ source('system_billing', 'usage') }} u
  LEFT JOIN price p
    ON u.sku_name = p.sku_name AND u.cloud = p.cloud AND u.usage_unit = p.usage_unit
   AND u.usage_end_time >= p.price_start_time
   AND (p.price_end_time IS NULL OR u.usage_end_time < p.price_end_time)
  WHERE upper(u.usage_unit) = 'DBU'
    AND u.usage_metadata.job_id IS NOT NULL
    AND u.usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
    AND u.usage_date <  {{ audit_today() }}
  GROUP BY u.workspace_id, u.usage_metadata.job_id
)
SELECT j.workspace_id, j.job_id,
       j.name AS name,
       r.last_run_start,
       j.create_time,
       COALESCE(cf.capture_floor_days, 0) AS capture_floor_days,
       CASE WHEN r.last_run_start IS NULL
              OR r.last_run_start < ({{ audit_today() }} - ({{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}) * INTERVAL 1 DAY)
            THEN 1 ELSE 0 END AS is_stale,
       COALESCE(cr.net_dbus, 0)     AS net_dbus,
       COALESCE(cr.est_usd_list, 0) AS est_usd_list,
       COALESCE(cr.price_basis, 'priced') AS price_basis,
       -- status: worst-first band on days since last run (field heuristic; {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }} / {{ param('lakeflow_stale_zombie_jobs', 'crit_stale_days', 90) }}).
       -- a NULL last_run_start is NOT_ASSESSED, never WARN/CRITICAL, while the job or this workspace's
       -- own capture history is too young to call it stale (too_young_to_call_stale).
       CASE
         WHEN r.last_run_start IS NULL
              AND (COALESCE(cf.capture_floor_days, 0) < {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}
                   OR j.create_time > ({{ audit_today() }} - ({{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}) * INTERVAL 1 DAY))
              THEN 'NOT_ASSESSED'
         WHEN r.last_run_start IS NULL THEN 'WARN'   -- confirmed no run in a long-enough capture window
         WHEN r.last_run_start < ({{ audit_today() }} - ({{ param('lakeflow_stale_zombie_jobs', 'crit_stale_days', 90) }}) * INTERVAL 1 DAY) THEN 'CRITICAL'
         WHEN r.last_run_start < ({{ audit_today() }} - ({{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}) * INTERVAL 1 DAY) THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN r.last_run_start IS NULL
              AND (COALESCE(cf.capture_floor_days, 0) < {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}
                   OR j.create_time > ({{ audit_today() }} - ({{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}) * INTERVAL 1 DAY))
              THEN 'too_young_to_call_stale'
       END AS not_assessed_reason
FROM latest_jobs j
LEFT JOIN last_run r       ON j.workspace_id = r.workspace_id AND j.job_id = r.job_id
LEFT JOIN capture_floor cf ON j.workspace_id = cf.workspace_id
LEFT JOIN cost_rollup cr   ON j.workspace_id = cr.workspace_id AND j.job_id = cr.job_id
WHERE j.delete_time IS NULL
ORDER BY last_run_start ASC
{%- else %}
WITH latest_jobs AS (
  SELECT workspace_id, job_id, name, run_as, creator_id, create_time, delete_time
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
),
last_run AS (
  SELECT workspace_id, job_id, MAX(period_start_time) AS last_run_start
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  GROUP BY workspace_id, job_id
),
capture_floor AS (
  -- how far back this WORKSPACE's own job_run_timeline history reaches, unfiltered by job
  SELECT workspace_id,
         datediff({{ audit_today() }}, MIN(period_start_time)) AS capture_floor_days
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  GROUP BY workspace_id
),
price AS (
  SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate
  FROM {{ list_prices() }} list_prices
),
cost_rollup AS (
  SELECT u.workspace_id,
         u.usage_metadata.job_id AS job_id,
         SUM(u.usage_quantity)                            AS net_dbus,
         SUM(u.usage_quantity * COALESCE(p.list_rate, 0)) AS est_usd_list,
         CASE
           WHEN SUM(CASE WHEN p.list_rate IS NULL AND upper(u.sku_name) NOT LIKE '%FREE_USAGE%'
                         THEN u.usage_quantity ELSE 0 END) > 0 THEN 'unpriced'
           WHEN SUM(CASE WHEN p.list_rate IS NOT NULL THEN u.usage_quantity ELSE 0 END) = 0 THEN 'free'
           ELSE 'priced'
         END                                               AS price_basis
  FROM {{ source('system_billing', 'usage') }} u
  LEFT JOIN price p
    ON u.sku_name = p.sku_name AND u.cloud = p.cloud AND u.usage_unit = p.usage_unit
   AND u.usage_end_time >= p.price_start_time
   AND (p.price_end_time IS NULL OR u.usage_end_time < p.price_end_time)
  WHERE upper(u.usage_unit) = 'DBU'
    AND u.usage_metadata.job_id IS NOT NULL
    AND u.usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
    AND u.usage_date <  {{ audit_today() }}
  GROUP BY u.workspace_id, u.usage_metadata.job_id
)
SELECT j.workspace_id, j.job_id,
       j.name AS name,
       r.last_run_start,
       j.create_time,
       COALESCE(cf.capture_floor_days, 0) AS capture_floor_days,
       CASE WHEN r.last_run_start IS NULL
              OR r.last_run_start < dateadd(day, -{{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}, {{ audit_today() }})
            THEN 1 ELSE 0 END AS is_stale,
       COALESCE(cr.net_dbus, 0)     AS net_dbus,
       COALESCE(cr.est_usd_list, 0) AS est_usd_list,
       COALESCE(cr.price_basis, 'priced') AS price_basis,
       -- status: worst-first band on days since last run (field heuristic; {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }} / {{ param('lakeflow_stale_zombie_jobs', 'crit_stale_days', 90) }}).
       -- a NULL last_run_start is NOT_ASSESSED, never WARN/CRITICAL, while the job or this workspace's
       -- own capture history is too young to call it stale (too_young_to_call_stale).
       CASE
         WHEN r.last_run_start IS NULL
              AND (COALESCE(cf.capture_floor_days, 0) < {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}
                   OR j.create_time > dateadd(day, -{{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}, {{ audit_today() }}))
              THEN 'NOT_ASSESSED'
         WHEN r.last_run_start IS NULL THEN 'WARN'   -- confirmed no run in a long-enough capture window
         WHEN r.last_run_start < dateadd(day, -{{ param('lakeflow_stale_zombie_jobs', 'crit_stale_days', 90) }}, {{ audit_today() }}) THEN 'CRITICAL'
         WHEN r.last_run_start < dateadd(day, -{{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}, {{ audit_today() }}) THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN r.last_run_start IS NULL
              AND (COALESCE(cf.capture_floor_days, 0) < {{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}
                   OR j.create_time > dateadd(day, -{{ param('lakeflow_stale_zombie_jobs', 'stale_days', 30) }}, {{ audit_today() }}))
              THEN 'too_young_to_call_stale'
       END AS not_assessed_reason
FROM latest_jobs j
LEFT JOIN last_run r       ON j.workspace_id = r.workspace_id AND j.job_id = r.job_id
LEFT JOIN capture_floor cf ON j.workspace_id = cf.workspace_id
LEFT JOIN cost_rollup cr   ON j.workspace_id = cr.workspace_id AND j.job_id = cr.job_id
WHERE j.delete_time IS NULL
ORDER BY last_run_start ASC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
