{{ config(materialized='table', tags=['inventory', 'domain:jobs_pipelines', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/jobs_pipelines/lakeflow_daily_state.sql (app-owned). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH run_rows AS (
  SELECT workspace_id, job_id, run_id, period_end_time, result_state,
         NULLIF(run_duration_seconds, 0) AS run_s_reported,
         MIN(period_start_time) OVER (PARTITION BY workspace_id, job_id, run_id) AS run_start
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  WHERE period_start_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
),
job_runs AS (
  SELECT 'job' AS resource_type, workspace_id, job_id AS resource_id, CAST(run_start AS DATE) AS usage_date,
         result_state,
         COALESCE(run_s_reported, date_diff('second', run_start, period_end_time)) AS run_s
  FROM run_rows
  WHERE result_state IS NOT NULL
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id, run_id ORDER BY period_end_time DESC) = 1
),
update_rows AS (
  SELECT workspace_id, pipeline_id, update_id, period_end_time, result_state,
         MIN(period_start_time) OVER (PARTITION BY workspace_id, pipeline_id, update_id) AS update_start
  FROM {{ source('system_lakeflow', 'pipeline_update_timeline') }}
  WHERE period_start_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
),
updates AS (
  SELECT 'pipeline' AS resource_type, workspace_id, pipeline_id AS resource_id, CAST(update_start AS DATE) AS usage_date,
         result_state,
         date_diff('second', update_start, period_end_time) AS run_s
  FROM update_rows
  WHERE result_state IS NOT NULL
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, pipeline_id, update_id ORDER BY period_end_time DESC) = 1
),
all_runs AS (
  SELECT * FROM job_runs
  UNION ALL SELECT * FROM updates
),
typical AS (
  SELECT resource_type, workspace_id, resource_id, quantile_cont(run_s, 0.5) AS median_run_s
  FROM all_runs
  WHERE result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED')
  GROUP BY resource_type, workspace_id, resource_id
),
daily AS (
  SELECT resource_type, workspace_id, resource_id, usage_date,
         COUNT(*) AS runs,
         SUM(CASE WHEN result_state IN ('FAILED', 'ERROR', 'TIMED_OUT') THEN 1 ELSE 0 END) AS failed,
         SUM(CASE WHEN result_state IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN 1 ELSE 0 END) AS skipped,
         SUM(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN 1 ELSE 0 END) AS timed_runs,
         SUM(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS total_run_s,
         MAX(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS max_run_s,
         AVG(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS avg_run_s
  FROM all_runs
  GROUP BY resource_type, workspace_id, resource_id, usage_date
),
stated AS (
SELECT d.usage_date,
       d.resource_type,
       concat(COALESCE(d.workspace_id, 'account'), ':', d.resource_id) AS resource_key,
       d.workspace_id,
       d.resource_id,
       d.runs,
       d.failed,
       d.skipped,
       d.timed_runs,
       ROUND(COALESCE(d.total_run_s, 0), 1) AS total_run_s,
       ROUND(d.max_run_s, 1) AS max_run_s,
       ROUND(d.avg_run_s, 1) AS avg_run_s,
       ROUND(t.median_run_s, 1) AS median_run_s,
       CASE
         WHEN d.failed > 0 THEN 'failed'
         WHEN d.avg_run_s IS NOT NULL AND t.median_run_s > 0
              AND d.avg_run_s >= {{ param('lakeflow_daily_state', 'slow_ratio', 1.5) }} * t.median_run_s
              AND d.avg_run_s - t.median_run_s >= {{ param('lakeflow_daily_state', 'slow_min_s', 60) }} THEN 'slow'
         WHEN d.skipped = d.runs THEN 'skipped'
         ELSE 'ok'
       END AS day_state
FROM daily d
LEFT JOIN typical t
  ON  t.resource_type = d.resource_type AND t.workspace_id IS NOT DISTINCT FROM d.workspace_id
  AND t.resource_id = d.resource_id
),
per_resource AS (
  SELECT stated.*,
         SUM(CASE WHEN day_state = 'failed' THEN 1 ELSE 0 END) OVER (PARTITION BY resource_type, resource_key) AS failed_days,
         SUM(CASE WHEN day_state = 'slow' THEN 1 ELSE 0 END) OVER (PARTITION BY resource_type, resource_key) AS slow_days,
         SUM(failed) OVER (PARTITION BY resource_type, resource_key) AS resource_failed
  FROM stated
)
SELECT usage_date, resource_type, resource_key, workspace_id, resource_id,
       CASE WHEN resource_type = 'job' THEN resource_id END AS job_id,
       CASE WHEN resource_type = 'pipeline' THEN resource_id END AS pipeline_id,
       runs, failed, skipped,
       timed_runs, total_run_s, max_run_s, avg_run_s, median_run_s, day_state, failed_days, slow_days,
       DENSE_RANK() OVER (ORDER BY failed_days DESC, slow_days DESC, resource_failed DESC,
                                   resource_type, resource_key) AS trouble_rank
FROM per_resource
ORDER BY trouble_rank, usage_date
{%- else %}
WITH run_rows AS (
  SELECT workspace_id, job_id, run_id, period_end_time, result_state,
         NULLIF(run_duration_seconds, 0) AS run_s_reported,
         MIN(period_start_time) OVER (PARTITION BY workspace_id, job_id, run_id) AS run_start
  FROM {{ source('system_lakeflow', 'job_run_timeline') }}
  WHERE period_start_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
),
job_runs AS (
  SELECT 'job' AS resource_type, workspace_id, job_id AS resource_id, date(run_start) AS usage_date,
         result_state,
         COALESCE(run_s_reported, timestampdiff(SECOND, run_start, period_end_time)) AS run_s
  FROM run_rows
  WHERE result_state IS NOT NULL
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id, run_id ORDER BY period_end_time DESC) = 1
),
update_rows AS (
  SELECT workspace_id, pipeline_id, update_id, period_end_time, result_state,
         MIN(period_start_time) OVER (PARTITION BY workspace_id, pipeline_id, update_id) AS update_start
  FROM {{ source('system_lakeflow', 'pipeline_update_timeline') }}
  WHERE period_start_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
),
updates AS (
  SELECT 'pipeline' AS resource_type, workspace_id, pipeline_id AS resource_id, date(update_start) AS usage_date,
         result_state,
         timestampdiff(SECOND, update_start, period_end_time) AS run_s
  FROM update_rows
  WHERE result_state IS NOT NULL
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, pipeline_id, update_id ORDER BY period_end_time DESC) = 1
),
all_runs AS (
  SELECT * FROM job_runs
  UNION ALL SELECT * FROM updates
),
typical AS (
  SELECT resource_type, workspace_id, resource_id, percentile(run_s, 0.5) AS median_run_s
  FROM all_runs
  WHERE result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED')
  GROUP BY resource_type, workspace_id, resource_id
),
daily AS (
  SELECT resource_type, workspace_id, resource_id, usage_date,
         COUNT(*) AS runs,
         SUM(CASE WHEN result_state IN ('FAILED', 'ERROR', 'TIMED_OUT') THEN 1 ELSE 0 END) AS failed,
         SUM(CASE WHEN result_state IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN 1 ELSE 0 END) AS skipped,
         SUM(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN 1 ELSE 0 END) AS timed_runs,
         SUM(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS total_run_s,
         MAX(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS max_run_s,
         AVG(CASE WHEN result_state NOT IN ('SKIPPED', 'CANCELED', 'CANCELLED') THEN run_s END) AS avg_run_s
  FROM all_runs
  GROUP BY resource_type, workspace_id, resource_id, usage_date
),
stated AS (
SELECT d.usage_date,
       d.resource_type,
       concat(COALESCE(d.workspace_id, 'account'), ':', d.resource_id) AS resource_key,
       d.workspace_id,
       d.resource_id,
       d.runs,
       d.failed,
       d.skipped,
       d.timed_runs,
       ROUND(COALESCE(d.total_run_s, 0), 1) AS total_run_s,
       ROUND(d.max_run_s, 1) AS max_run_s,
       ROUND(d.avg_run_s, 1) AS avg_run_s,
       ROUND(t.median_run_s, 1) AS median_run_s,
       CASE
         WHEN d.failed > 0 THEN 'failed'
         WHEN d.avg_run_s IS NOT NULL AND t.median_run_s > 0
              AND d.avg_run_s >= {{ param('lakeflow_daily_state', 'slow_ratio', 1.5) }} * t.median_run_s
              AND d.avg_run_s - t.median_run_s >= {{ param('lakeflow_daily_state', 'slow_min_s', 60) }} THEN 'slow'
         WHEN d.skipped = d.runs THEN 'skipped'
         ELSE 'ok'
       END AS day_state
FROM daily d
LEFT JOIN typical t
  ON  t.resource_type = d.resource_type AND t.workspace_id IS NOT DISTINCT FROM d.workspace_id
  AND t.resource_id = d.resource_id
),
per_resource AS (
  SELECT stated.*,
         SUM(CASE WHEN day_state = 'failed' THEN 1 ELSE 0 END) OVER (PARTITION BY resource_type, resource_key) AS failed_days,
         SUM(CASE WHEN day_state = 'slow' THEN 1 ELSE 0 END) OVER (PARTITION BY resource_type, resource_key) AS slow_days,
         SUM(failed) OVER (PARTITION BY resource_type, resource_key) AS resource_failed
  FROM stated
)
SELECT usage_date, resource_type, resource_key, workspace_id, resource_id,
       CASE WHEN resource_type = 'job' THEN resource_id END AS job_id,
       CASE WHEN resource_type = 'pipeline' THEN resource_id END AS pipeline_id,
       runs, failed, skipped,
       timed_runs, total_run_s, max_run_s, avg_run_s, median_run_s, day_state, failed_days, slow_days,
       DENSE_RANK() OVER (ORDER BY failed_days DESC, slow_days DESC, resource_failed DESC,
                                   resource_type, resource_key) AS trouble_rank
FROM per_resource
ORDER BY trouble_rank, usage_date
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
