{{ config(materialized='table', tags=['finding', 'domain:jobs_pipelines', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/jobs_pipelines/lakeflow_tasks_near_timeout.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH latest_tasks AS (
  SELECT workspace_id, job_id, task_key, timeout_seconds, delete_time
  FROM {{ source('system_lakeflow', 'job_tasks') }}
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY workspace_id, job_id, task_key ORDER BY change_time DESC
  ) = 1
),
latest_jobs AS (
  SELECT workspace_id, job_id, name AS job_name
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
),
task_end AS (
  SELECT workspace_id, job_id, task_key, run_id, execution_duration_seconds
  FROM {{ source('system_lakeflow', 'job_task_run_timeline') }}
  WHERE period_start_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})   -- drop incomplete current day
    AND result_state IS NOT NULL                                   -- task end row only
),
agg AS (
  SELECT t.workspace_id, t.job_id, t.task_key,
         lt.timeout_seconds,
         COUNT(DISTINCT t.run_id)                              AS task_runs,
         MAX(t.execution_duration_seconds)                     AS max_exec_s,
         quantile_cont(t.execution_duration_seconds, 0.95) AS exec_s_p95,
         -- runs whose execution reached >= {{ param('lakeflow_tasks_near_timeout', 'near_timeout_ratio', 0.8) }} of a CONFIGURED (>0) timeout but
         -- stayed under it -- mutually exclusive with runs_over_timeout, so the two never overlap.
         SUM(CASE WHEN lt.timeout_seconds > 0
                   AND t.execution_duration_seconds >= {{ param('lakeflow_tasks_near_timeout', 'near_timeout_ratio', 0.8) }} * lt.timeout_seconds
                   AND t.execution_duration_seconds <  lt.timeout_seconds
                  THEN 1 ELSE 0 END) AS runs_near_timeout,
         -- runs that ran AT/PAST the configured timeout (should have been killed)
         SUM(CASE WHEN lt.timeout_seconds > 0
                   AND t.execution_duration_seconds >= lt.timeout_seconds
                  THEN 1 ELSE 0 END) AS runs_over_timeout,
         -- an explicit 0-second timeout is "no bound configured" (a deliberate setting, not a gap).
         SUM(CASE WHEN lt.timeout_seconds = 0 THEN 1 ELSE 0 END) AS runs_no_timeout_bound,
         -- degradation buckets: a NULL timeout / NULL execution duration is "column not yet
         -- populated" (not assessed), distinct from an explicit 0-second timeout above.
         SUM(CASE WHEN lt.timeout_seconds IS NULL THEN 1 ELSE 0 END) AS runs_no_task_timeout,
         SUM(CASE WHEN t.execution_duration_seconds IS NULL THEN 1 ELSE 0 END) AS runs_exec_null
  FROM task_end t
  LEFT JOIN latest_tasks lt
    ON  t.workspace_id = lt.workspace_id
    AND t.job_id       = lt.job_id
    AND t.task_key     = lt.task_key
  GROUP BY t.workspace_id, t.job_id, t.task_key, lt.timeout_seconds
)
SELECT a.workspace_id, a.job_id, j.job_name, w.workspace_name, a.task_key, a.timeout_seconds,
       a.task_runs, a.max_exec_s, a.exec_s_p95,
       a.runs_near_timeout, a.runs_over_timeout, a.runs_no_timeout_bound,
       a.runs_no_task_timeout, a.runs_exec_null,
       -- status: worst-first band on near/over-timeout run count (field heuristic;
       -- {{ param('lakeflow_tasks_near_timeout', 'warn_near_timeout_runs', 3) }} / {{ param('lakeflow_tasks_near_timeout', 'crit_near_timeout_runs', 10) }}), degraded to NOT_ASSESSED when either
       -- NULL bucket accounts for a material share of the task's runs.
       CASE
         WHEN a.runs_no_task_timeout >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'NOT_ASSESSED'
         WHEN a.runs_exec_null       >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'NOT_ASSESSED'
         WHEN (a.runs_near_timeout + a.runs_over_timeout) >= {{ param('lakeflow_tasks_near_timeout', 'crit_near_timeout_runs', 10) }} THEN 'CRITICAL'
         WHEN (a.runs_near_timeout + a.runs_over_timeout) >= {{ param('lakeflow_tasks_near_timeout', 'warn_near_timeout_runs', 3) }} THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN a.runs_no_task_timeout >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'timeout_not_populated'
         WHEN a.runs_exec_null       >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'exec_duration_not_populated'
       END AS not_assessed_reason
FROM agg a
LEFT JOIN latest_jobs j ON j.workspace_id = a.workspace_id AND j.job_id = a.job_id
LEFT JOIN {{ source('system_access', 'workspaces_latest') }} w ON w.workspace_id = a.workspace_id
ORDER BY (a.runs_near_timeout + a.runs_over_timeout) DESC
{%- else %}
WITH latest_tasks AS (
  SELECT workspace_id, job_id, task_key, timeout_seconds, delete_time
  FROM {{ source('system_lakeflow', 'job_tasks') }}
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY workspace_id, job_id, task_key ORDER BY change_time DESC
  ) = 1
),
latest_jobs AS (
  SELECT workspace_id, job_id, name AS job_name
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
),
task_end AS (
  SELECT workspace_id, job_id, task_key, run_id, execution_duration_seconds
  FROM {{ source('system_lakeflow', 'job_task_run_timeline') }}
  WHERE period_start_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
    AND period_end_time < date_trunc('DAY', {{ audit_now() }})   -- drop incomplete current day
    AND result_state IS NOT NULL                                   -- task end row only
),
agg AS (
  SELECT t.workspace_id, t.job_id, t.task_key,
         lt.timeout_seconds,
         COUNT(DISTINCT t.run_id)                              AS task_runs,
         MAX(t.execution_duration_seconds)                     AS max_exec_s,
         percentile(t.execution_duration_seconds, 0.95) AS exec_s_p95,
         -- runs whose execution reached >= {{ param('lakeflow_tasks_near_timeout', 'near_timeout_ratio', 0.8) }} of a CONFIGURED (>0) timeout but
         -- stayed under it -- mutually exclusive with runs_over_timeout, so the two never overlap.
         SUM(CASE WHEN lt.timeout_seconds > 0
                   AND t.execution_duration_seconds >= {{ param('lakeflow_tasks_near_timeout', 'near_timeout_ratio', 0.8) }} * lt.timeout_seconds
                   AND t.execution_duration_seconds <  lt.timeout_seconds
                  THEN 1 ELSE 0 END) AS runs_near_timeout,
         -- runs that ran AT/PAST the configured timeout (should have been killed)
         SUM(CASE WHEN lt.timeout_seconds > 0
                   AND t.execution_duration_seconds >= lt.timeout_seconds
                  THEN 1 ELSE 0 END) AS runs_over_timeout,
         -- an explicit 0-second timeout is "no bound configured" (a deliberate setting, not a gap).
         SUM(CASE WHEN lt.timeout_seconds = 0 THEN 1 ELSE 0 END) AS runs_no_timeout_bound,
         -- degradation buckets: a NULL timeout / NULL execution duration is "column not yet
         -- populated" (not assessed), distinct from an explicit 0-second timeout above.
         SUM(CASE WHEN lt.timeout_seconds IS NULL THEN 1 ELSE 0 END) AS runs_no_task_timeout,
         SUM(CASE WHEN t.execution_duration_seconds IS NULL THEN 1 ELSE 0 END) AS runs_exec_null
  FROM task_end t
  LEFT JOIN latest_tasks lt
    ON  t.workspace_id = lt.workspace_id
    AND t.job_id       = lt.job_id
    AND t.task_key     = lt.task_key
  GROUP BY t.workspace_id, t.job_id, t.task_key, lt.timeout_seconds
)
SELECT a.workspace_id, a.job_id, j.job_name, w.workspace_name, a.task_key, a.timeout_seconds,
       a.task_runs, a.max_exec_s, a.exec_s_p95,
       a.runs_near_timeout, a.runs_over_timeout, a.runs_no_timeout_bound,
       a.runs_no_task_timeout, a.runs_exec_null,
       -- status: worst-first band on near/over-timeout run count (field heuristic;
       -- {{ param('lakeflow_tasks_near_timeout', 'warn_near_timeout_runs', 3) }} / {{ param('lakeflow_tasks_near_timeout', 'crit_near_timeout_runs', 10) }}), degraded to NOT_ASSESSED when either
       -- NULL bucket accounts for a material share of the task's runs.
       CASE
         WHEN a.runs_no_task_timeout >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'NOT_ASSESSED'
         WHEN a.runs_exec_null       >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'NOT_ASSESSED'
         WHEN (a.runs_near_timeout + a.runs_over_timeout) >= {{ param('lakeflow_tasks_near_timeout', 'crit_near_timeout_runs', 10) }} THEN 'CRITICAL'
         WHEN (a.runs_near_timeout + a.runs_over_timeout) >= {{ param('lakeflow_tasks_near_timeout', 'warn_near_timeout_runs', 3) }} THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN a.runs_no_task_timeout >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'timeout_not_populated'
         WHEN a.runs_exec_null       >= {{ param('lakeflow_tasks_near_timeout', 'null_bucket_material_share', 0.5) }} * a.task_runs THEN 'exec_duration_not_populated'
       END AS not_assessed_reason
FROM agg a
LEFT JOIN latest_jobs j ON j.workspace_id = a.workspace_id AND j.job_id = a.job_id
LEFT JOIN {{ source('system_access', 'workspaces_latest') }} w ON w.workspace_id = a.workspace_id
ORDER BY (a.runs_near_timeout + a.runs_over_timeout) DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
