{{ config(materialized='table', tags=['finding', 'domain:governance_access', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/governance_access/access_delta_sharing_exposure.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH recips AS (
  SELECT SHARE_NAME,
         COUNT(DISTINCT RECIPIENT_NAME) AS recipient_count,
         array_to_string(list_distinct(list({{ mask_user('RECIPIENT_NAME') }})), ', ') AS recipients
  FROM {{ source('system_information_schema', 'share_recipient_privileges') }}
  GROUP BY SHARE_NAME
),
tbls AS (
  SELECT SHARE_NAME, COUNT(*) AS shared_table_count
  FROM {{ source('system_information_schema', 'table_share_usage') }} GROUP BY SHARE_NAME
),
schs AS (
  SELECT SHARE_NAME, COUNT(*) AS shared_schema_count
  FROM {{ source('system_information_schema', 'schema_share_usage') }} GROUP BY SHARE_NAME
)
SELECT
  s.SHARE_NAME                                              AS share_name,
  {{ mask_user('s.SHARE_OWNER') }} AS share_owner,
  COALESCE(r.recipient_count, 0)                            AS recipient_count,
  r.recipients                                             AS recipients,
  COALESCE(t.shared_table_count, 0)                        AS shared_table_count,
  COALESCE(sc.shared_schema_count, 0)                      AS shared_schema_count,
  s.CREATED                                                AS created,
  CASE
    WHEN COALESCE(r.recipient_count, 0) >= {{ param('access_delta_sharing_exposure', 'crit_share_recipients', 10) }}
      OR COALESCE(t.shared_table_count, 0) >= {{ param('access_delta_sharing_exposure', 'crit_shared_tables', 100) }}       THEN 'CRITICAL'
    WHEN COALESCE(r.recipient_count, 0) >= {{ param('access_delta_sharing_exposure', 'warn_share_recipients', 1) }}       THEN 'WARN'
    ELSE 'OK'
  END AS status
FROM {{ source('system_information_schema', 'shares') }} s
LEFT JOIN recips r  ON r.SHARE_NAME  = s.SHARE_NAME
LEFT JOIN tbls   t  ON t.SHARE_NAME  = s.SHARE_NAME
LEFT JOIN schs   sc ON sc.SHARE_NAME = s.SHARE_NAME
ORDER BY
  CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
  recipient_count DESC, shared_table_count DESC
LIMIT {{ param('access_delta_sharing_exposure', 'top_n', 200) }}
{%- else %}
WITH recips AS (
  SELECT SHARE_NAME,
         COUNT(DISTINCT RECIPIENT_NAME) AS recipient_count,
         array_join(collect_set(
           {{ mask_user('RECIPIENT_NAME') }}), ', ') AS recipients
  FROM {{ source('system_information_schema', 'share_recipient_privileges') }}
  GROUP BY SHARE_NAME
),
tbls AS (
  SELECT SHARE_NAME, COUNT(*) AS shared_table_count
  FROM {{ source('system_information_schema', 'table_share_usage') }} GROUP BY SHARE_NAME
),
schs AS (
  SELECT SHARE_NAME, COUNT(*) AS shared_schema_count
  FROM {{ source('system_information_schema', 'schema_share_usage') }} GROUP BY SHARE_NAME
)
SELECT
  s.SHARE_NAME                                              AS share_name,
  {{ mask_user('s.SHARE_OWNER') }} AS share_owner,
  COALESCE(r.recipient_count, 0)                            AS recipient_count,
  r.recipients                                             AS recipients,
  COALESCE(t.shared_table_count, 0)                        AS shared_table_count,
  COALESCE(sc.shared_schema_count, 0)                      AS shared_schema_count,
  s.CREATED                                                AS created,
  CASE
    WHEN COALESCE(r.recipient_count, 0) >= {{ param('access_delta_sharing_exposure', 'crit_share_recipients', 10) }}
      OR COALESCE(t.shared_table_count, 0) >= {{ param('access_delta_sharing_exposure', 'crit_shared_tables', 100) }}       THEN 'CRITICAL'
    WHEN COALESCE(r.recipient_count, 0) >= {{ param('access_delta_sharing_exposure', 'warn_share_recipients', 1) }}       THEN 'WARN'
    ELSE 'OK'
  END AS status
FROM {{ source('system_information_schema', 'shares') }} s
LEFT JOIN recips r  ON r.SHARE_NAME  = s.SHARE_NAME
LEFT JOIN tbls   t  ON t.SHARE_NAME  = s.SHARE_NAME
LEFT JOIN schs   sc ON sc.SHARE_NAME = s.SHARE_NAME
ORDER BY
  CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
  recipient_count DESC, shared_table_count DESC
LIMIT {{ param('access_delta_sharing_exposure', 'top_n', 200) }}
{%- endif %}
) q
