{{ config(materialized='table', tags=['inventory', 'domain:governance_access', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/governance_access/access_row_filters_inventory.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT table_catalog, table_schema, table_name,
       filter_name, target_columns
FROM {{ source('system_information_schema', 'row_filters') }}
ORDER BY table_catalog, table_schema, table_name
{%- else %}
SELECT table_catalog, table_schema, table_name,
       filter_name, target_columns
FROM {{ source('system_information_schema', 'row_filters') }}
ORDER BY table_catalog, table_schema, table_name
{%- endif %}
) q
