{{ config(materialized='table', tags=['finding', 'domain:governance_access', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/governance_access/access_broad_grants.sql (app-owned). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH table_grants AS (
  SELECT
    'TABLE'                                                    AS securable_type,
    CONCAT(TABLE_CATALOG, '.', TABLE_SCHEMA, '.', TABLE_NAME)  AS securable,
    GRANTEE                                                    AS raw_grantee,
    PRIVILEGE_TYPE                                             AS privilege_type,
    (INHERITED_FROM IS NOT NULL)                               AS is_inherited,
    INHERITED_FROM                                             AS inherited_from,
    TABLE_CATALOG                                              AS cat,
    TABLE_SCHEMA                                               AS sch
  FROM {{ source('system_information_schema', 'table_privileges') }}
),
catalog_grants AS (
  SELECT
    'CATALOG'                       AS securable_type,
    CATALOG_NAME                    AS securable,
    GRANTEE                         AS raw_grantee,
    PRIVILEGE_TYPE                  AS privilege_type,
    CAST(NULL AS BOOLEAN)           AS is_inherited,   -- not tracked by this source; see caveats
    CAST(NULL AS STRING)            AS inherited_from,
    CATALOG_NAME                    AS cat,
    CAST(NULL AS STRING)            AS sch
  FROM {{ source('system_information_schema', 'catalog_privileges') }}
),
schema_grants AS (
  SELECT
    'SCHEMA'                                AS securable_type,
    CONCAT(CATALOG_NAME, '.', SCHEMA_NAME)  AS securable,
    GRANTEE                                 AS raw_grantee,
    PRIVILEGE_TYPE                          AS privilege_type,
    CAST(NULL AS BOOLEAN)                   AS is_inherited,   -- not tracked by this source; see caveats
    CAST(NULL AS STRING)                    AS inherited_from,
    CATALOG_NAME                            AS cat,
    SCHEMA_NAME                             AS sch
  FROM {{ source('system_information_schema', 'schema_privileges') }}
),
grants AS (
  SELECT * FROM table_grants
  UNION ALL
  SELECT * FROM catalog_grants
  UNION ALL
  SELECT * FROM schema_grants
),
own_grants AS (
  SELECT g.*
  FROM grants g
  LEFT JOIN (SELECT DISTINCT cat, raw_grantee, privilege_type FROM catalog_grants) pc
    ON g.securable_type <> 'CATALOG' AND pc.cat = g.cat
   AND pc.raw_grantee = g.raw_grantee AND pc.privilege_type = g.privilege_type
  LEFT JOIN (SELECT DISTINCT cat, sch, raw_grantee, privilege_type FROM schema_grants) ps
    ON g.securable_type = 'TABLE' AND ps.cat = g.cat AND ps.sch = g.sch
   AND ps.raw_grantee = g.raw_grantee AND ps.privilege_type = g.privilege_type
  WHERE pc.cat IS NULL AND ps.cat IS NULL
),
classified AS (
  SELECT g.*,
         -- field heuristic, no dedicated principal-type column exists in either source (caveats)
         CASE
           WHEN g.raw_grantee IS NULL OR g.raw_grantee = '__REDACTED__'                    THEN 'UNKNOWN'
           WHEN LOWER(TRIM(g.raw_grantee)) IN ('account users', 'all account users', 'users') THEN 'ALL_USERS'
           WHEN regexp_matches(g.raw_grantee, '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$') THEN 'SERVICE_PRINCIPAL'
           WHEN g.raw_grantee LIKE '%@%'                                                   THEN 'USER'
           ELSE 'GROUP'
         END AS grantee_type
  FROM own_grants g
),
flagged AS (
  SELECT c.*,
         (c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES'))                 AS is_all_privileges,
         (c.grantee_type = 'ALL_USERS')                                             AS is_all_users,
         (c.grantee_type = 'GROUP' AND c.privilege_type IN ('MANAGE', 'OWNERSHIP')) AS is_manage_to_group,
         -- write, ANY scope: MODIFY, any CREATE_* privilege, or ALL PRIVILEGES. Judged on its own
         -- (no scope limit) so a write grant to every user in the account is CRITICAL no matter
         -- where it is granted; see is_write_at_catalog below for the scope-limited rule that
         -- still applies to a named (non all-users) principal.
         (c.privilege_type = 'MODIFY'
           OR c.privilege_type LIKE 'CREATE%'
           OR c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES'))             AS is_write,
         -- write, catalog or schema scope (caveats): same privilege set, but only counts as broad
         -- on its own (for a named, non all-users principal) when granted at CATALOG or SCHEMA
         -- scope -- a schema-level write grant reaches every table the schema holds now and
         -- later, the same leverage as a catalog-level one.
         (c.securable_type IN ('CATALOG', 'SCHEMA')
           AND (c.privilege_type = 'MODIFY'
             OR c.privilege_type LIKE 'CREATE%'
             OR c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES')))          AS is_write_at_catalog_or_schema
  FROM classified c
)
SELECT
  f.securable_type,
  f.securable,
  f.grantee_type,
  CASE
    WHEN f.raw_grantee IS NULL OR f.raw_grantee = '__REDACTED__' THEN f.raw_grantee
    WHEN f.grantee_type = 'SERVICE_PRINCIPAL'                    THEN f.raw_grantee
    WHEN f.grantee_type = 'USER'
      THEN (
        {{ mask_user('f.raw_grantee') }}
      )
    ELSE f.raw_grantee   -- GROUP or ALL_USERS: not personal data, shown in full
  END AS grantee,
  f.privilege_type,
  f.is_inherited,
  f.inherited_from,
  CASE
    WHEN f.is_all_privileges AND f.grantee_type = 'USER'      THEN 'ALL PRIVILEGES granted to a person, not a group'
    WHEN f.is_all_users AND f.is_write                       THEN 'write privilege granted to every user in the account'
    WHEN f.is_all_privileges                                THEN 'ALL PRIVILEGES granted to a group or service principal'
    WHEN f.is_all_users                                      THEN 'granted to every user in the account'
    WHEN f.is_manage_to_group                                THEN 'MANAGE (near-ownership) privilege granted to a group'
    WHEN f.is_write_at_catalog_or_schema                      THEN 'write privilege granted at catalog or schema level'
    ELSE NULL
  END AS reason,
  -- status: a WARN must have a lever, same discipline as every other verdict in this library.
  -- ALL PRIVILEGES to a person, or a write privilege granted to everyone (any scope), is the
  -- highest-leverage case; ALL PRIVILEGES to a group is usually an admin group.
  CASE
    WHEN f.is_all_privileges AND f.grantee_type = 'USER' THEN 'CRITICAL'
    WHEN f.is_all_users AND f.is_write            THEN 'CRITICAL'
    WHEN f.is_all_privileges OR f.is_all_users OR f.is_manage_to_group OR f.is_write_at_catalog_or_schema THEN 'WARN'
    ELSE 'OK'   -- unreachable: the WHERE clause below only ever admits a broad row
  END AS status
FROM flagged f
WHERE f.is_all_privileges OR f.is_all_users OR f.is_manage_to_group OR f.is_write_at_catalog_or_schema
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
         securable_type, securable, privilege_type, grantee
LIMIT {{ param('access_broad_grants', 'top_n', 100000) }}
{%- else %}
WITH table_grants AS (
  SELECT
    'TABLE'                                                    AS securable_type,
    CONCAT(TABLE_CATALOG, '.', TABLE_SCHEMA, '.', TABLE_NAME)  AS securable,
    GRANTEE                                                    AS raw_grantee,
    PRIVILEGE_TYPE                                             AS privilege_type,
    (INHERITED_FROM IS NOT NULL)                               AS is_inherited,
    INHERITED_FROM                                             AS inherited_from,
    TABLE_CATALOG                                              AS cat,
    TABLE_SCHEMA                                               AS sch
  FROM {{ source('system_information_schema', 'table_privileges') }}
),
catalog_grants AS (
  SELECT
    'CATALOG'                       AS securable_type,
    CATALOG_NAME                    AS securable,
    GRANTEE                         AS raw_grantee,
    PRIVILEGE_TYPE                  AS privilege_type,
    CAST(NULL AS BOOLEAN)           AS is_inherited,   -- not tracked by this source; see caveats
    CAST(NULL AS STRING)            AS inherited_from,
    CATALOG_NAME                    AS cat,
    CAST(NULL AS STRING)            AS sch
  FROM {{ source('system_information_schema', 'catalog_privileges') }}
),
schema_grants AS (
  SELECT
    'SCHEMA'                                AS securable_type,
    CONCAT(CATALOG_NAME, '.', SCHEMA_NAME)  AS securable,
    GRANTEE                                 AS raw_grantee,
    PRIVILEGE_TYPE                          AS privilege_type,
    CAST(NULL AS BOOLEAN)                   AS is_inherited,   -- not tracked by this source; see caveats
    CAST(NULL AS STRING)                    AS inherited_from,
    CATALOG_NAME                            AS cat,
    SCHEMA_NAME                             AS sch
  FROM {{ source('system_information_schema', 'schema_privileges') }}
),
grants AS (
  SELECT * FROM table_grants
  UNION ALL
  SELECT * FROM catalog_grants
  UNION ALL
  SELECT * FROM schema_grants
),
own_grants AS (
  SELECT g.*
  FROM grants g
  LEFT JOIN (SELECT DISTINCT cat, raw_grantee, privilege_type FROM catalog_grants) pc
    ON g.securable_type <> 'CATALOG' AND pc.cat = g.cat
   AND pc.raw_grantee = g.raw_grantee AND pc.privilege_type = g.privilege_type
  LEFT JOIN (SELECT DISTINCT cat, sch, raw_grantee, privilege_type FROM schema_grants) ps
    ON g.securable_type = 'TABLE' AND ps.cat = g.cat AND ps.sch = g.sch
   AND ps.raw_grantee = g.raw_grantee AND ps.privilege_type = g.privilege_type
  WHERE pc.cat IS NULL AND ps.cat IS NULL
),
classified AS (
  SELECT g.*,
         -- field heuristic, no dedicated principal-type column exists in either source (caveats)
         CASE
           WHEN g.raw_grantee IS NULL OR g.raw_grantee = '__REDACTED__'                    THEN 'UNKNOWN'
           WHEN LOWER(TRIM(g.raw_grantee)) IN ('account users', 'all account users', 'users') THEN 'ALL_USERS'
           WHEN g.raw_grantee RLIKE '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN 'SERVICE_PRINCIPAL'
           WHEN g.raw_grantee LIKE '%@%'                                                   THEN 'USER'
           ELSE 'GROUP'
         END AS grantee_type
  FROM own_grants g
),
flagged AS (
  SELECT c.*,
         (c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES'))                 AS is_all_privileges,
         (c.grantee_type = 'ALL_USERS')                                             AS is_all_users,
         (c.grantee_type = 'GROUP' AND c.privilege_type IN ('MANAGE', 'OWNERSHIP')) AS is_manage_to_group,
         -- write, ANY scope: MODIFY, any CREATE_* privilege, or ALL PRIVILEGES. Judged on its own
         -- (no scope limit) so a write grant to every user in the account is CRITICAL no matter
         -- where it is granted; see is_write_at_catalog below for the scope-limited rule that
         -- still applies to a named (non all-users) principal.
         (c.privilege_type = 'MODIFY'
           OR c.privilege_type LIKE 'CREATE%'
           OR c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES'))             AS is_write,
         -- write, catalog or schema scope (caveats): same privilege set, but only counts as broad
         -- on its own (for a named, non all-users principal) when granted at CATALOG or SCHEMA
         -- scope -- a schema-level write grant reaches every table the schema holds now and
         -- later, the same leverage as a catalog-level one.
         (c.securable_type IN ('CATALOG', 'SCHEMA')
           AND (c.privilege_type = 'MODIFY'
             OR c.privilege_type LIKE 'CREATE%'
             OR c.privilege_type IN ('ALL PRIVILEGES', 'ALL_PRIVILEGES')))          AS is_write_at_catalog_or_schema
  FROM classified c
)
SELECT
  f.securable_type,
  f.securable,
  f.grantee_type,
  CASE
    WHEN f.raw_grantee IS NULL OR f.raw_grantee = '__REDACTED__' THEN f.raw_grantee
    WHEN f.grantee_type = 'SERVICE_PRINCIPAL'                    THEN f.raw_grantee
    WHEN f.grantee_type = 'USER'
      THEN (
        {{ mask_user('f.raw_grantee') }}
      )
    ELSE f.raw_grantee   -- GROUP or ALL_USERS: not personal data, shown in full
  END AS grantee,
  f.privilege_type,
  f.is_inherited,
  f.inherited_from,
  CASE
    WHEN f.is_all_privileges AND f.grantee_type = 'USER'      THEN 'ALL PRIVILEGES granted to a person, not a group'
    WHEN f.is_all_users AND f.is_write                       THEN 'write privilege granted to every user in the account'
    WHEN f.is_all_privileges                                THEN 'ALL PRIVILEGES granted to a group or service principal'
    WHEN f.is_all_users                                      THEN 'granted to every user in the account'
    WHEN f.is_manage_to_group                                THEN 'MANAGE (near-ownership) privilege granted to a group'
    WHEN f.is_write_at_catalog_or_schema                      THEN 'write privilege granted at catalog or schema level'
    ELSE NULL
  END AS reason,
  -- status: a WARN must have a lever, same discipline as every other verdict in this library.
  -- ALL PRIVILEGES to a person, or a write privilege granted to everyone (any scope), is the
  -- highest-leverage case; ALL PRIVILEGES to a group is usually an admin group.
  CASE
    WHEN f.is_all_privileges AND f.grantee_type = 'USER' THEN 'CRITICAL'
    WHEN f.is_all_users AND f.is_write            THEN 'CRITICAL'
    WHEN f.is_all_privileges OR f.is_all_users OR f.is_manage_to_group OR f.is_write_at_catalog_or_schema THEN 'WARN'
    ELSE 'OK'   -- unreachable: the WHERE clause below only ever admits a broad row
  END AS status
FROM flagged f
WHERE f.is_all_privileges OR f.is_all_users OR f.is_manage_to_group OR f.is_write_at_catalog_or_schema
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
         securable_type, securable, privilege_type, grantee
LIMIT {{ param('access_broad_grants', 'top_n', 100000) }}
{%- endif %}
) q
