{{ config(materialized='table', tags=['inventory', 'domain:governance_access', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/governance_access/access_data_classification_inventory.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT catalog_name, schema_name, table_name, column_name, class_tag, confidence, data_type,
       MAX(frequency)            AS max_frequency,
       MAX(latest_detected_time) AS latest_detected_time,
       MIN(first_detected_time)  AS first_detected_time
FROM {{ source('system_data_classification', 'results') }}
WHERE class_tag IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6, 7
ORDER BY catalog_name, schema_name, table_name, column_name
{%- else %}
SELECT catalog_name, schema_name, table_name, column_name, class_tag, confidence, data_type,
       MAX(frequency)            AS max_frequency,
       MAX(latest_detected_time) AS latest_detected_time,
       MIN(first_detected_time)  AS first_detected_time
FROM {{ source('system_data_classification', 'results') }}
WHERE class_tag IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6, 7
ORDER BY catalog_name, schema_name, table_name, column_name
{%- endif %}
) q
