{{ config(materialized='table', tags=['inventory', 'domain:governance_access', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/governance_access/access_column_masks_inventory.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT table_catalog, table_schema, table_name, column_name,
       mask_name, using_columns
FROM {{ source('system_information_schema', 'column_masks') }}
ORDER BY table_catalog, table_schema, table_name, column_name
{%- else %}
SELECT table_catalog, table_schema, table_name, column_name,
       mask_name, using_columns
FROM {{ source('system_information_schema', 'column_masks') }}
ORDER BY table_catalog, table_schema, table_name, column_name
{%- endif %}
) q
