{{ config(materialized='table', tags=['finding', 'domain:governance_access', 'tier:deep']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/governance_access/access_network_outbound_denials.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT workspace_id, network_source_type, destination_type, access_type, destination,
       dns_event.rcode                AS dns_rcode,
       storage_event.rejection_reason AS storage_rejection_reason,
       COUNT(*) AS denial_count,
       MIN(event_time) AS first_event_time, MAX(event_time) AS last_event_time,
       -- status: worst-first band on outbound denial volume per workspace+source+destination combo (field heuristic; {{ param('access_network_outbound_denials', 'warn_denial_count', 10) }} / {{ param('access_network_outbound_denials', 'crit_denial_count', 50) }}).
       CASE
         WHEN COUNT(*) >= {{ param('access_network_outbound_denials', 'crit_denial_count', 50) }} THEN 'CRITICAL'
         WHEN COUNT(*) >= {{ param('access_network_outbound_denials', 'warn_denial_count', 10) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_access', 'outbound_network') }}
WHERE event_time >= {{ audit_now() }} - (({{ w }}) * INTERVAL 1 DAY)
GROUP BY 1, 2, 3, 4, 5, 6, 7
ORDER BY denial_count DESC
{%- else %}
SELECT workspace_id, network_source_type, destination_type, access_type, destination,
       dns_event.rcode                AS dns_rcode,
       storage_event.rejection_reason AS storage_rejection_reason,
       COUNT(*) AS denial_count,
       MIN(event_time) AS first_event_time, MAX(event_time) AS last_event_time,
       -- status: worst-first band on outbound denial volume per workspace+source+destination combo (field heuristic; {{ param('access_network_outbound_denials', 'warn_denial_count', 10) }} / {{ param('access_network_outbound_denials', 'crit_denial_count', 50) }}).
       CASE
         WHEN COUNT(*) >= {{ param('access_network_outbound_denials', 'crit_denial_count', 50) }} THEN 'CRITICAL'
         WHEN COUNT(*) >= {{ param('access_network_outbound_denials', 'warn_denial_count', 10) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_access', 'outbound_network') }}
WHERE event_time >= {{ audit_now() }} - INTERVAL {{ w }} DAYS
GROUP BY 1, 2, 3, 4, 5, 6, 7
ORDER BY denial_count DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
