#!/usr/bin/env python3
"""tools/generate_models.py -- vendored / app-owned queries -> dbt models (PLAN.md section 5.3).

    python tools/generate_models.py                       every executable query (113 today: 100 vendored + 13 app-owned)
    python tools/generate_models.py --only <id> [<id>..]  just those query ids
    python tools/generate_models.py --domain <name>       just that domain
    python tools/generate_models.py --check [scope]       exit 1 listing stale / missing / extra files
    python tools/generate_models.py --force               overwrite a model / yml file that lacks
                                                          the GENERATED marker (a hand-written file
                                                          in the way is otherwise refused)

Per executable query (registry `executable` flag; the DESCRIBE/ANALYZE templates are skipped
with a reason and listed under `skipped` in generated_manifest.json):

  1. body     = QuerySpec.body with every line starting with `--` dropped, trailing `;` removed --
                exactly the public runner's tools/run_audit.py resolve_sql() stripping rule.
                Guard: the body must start with SELECT/WITH, must not contain a Jinja delimiter
                and must not name a column `window_days`.
  2. tokens   = `:period_days` -> `__W__`, any other param the header declares -> `__P__<name>__`
                (longest-name-first alternation, the runner's own rule, so `':00'` in a time
                literal is untouched); any other `:name` outside a literal/comment is an error.
  2b. tokens  = app.core.translate.strip_resource_mask(tokens) then .mask_user_identities(tokens):
                a resource-name preview CASE -> the plain column; an identity-mask CASE -> one
                `{{ mask_user(...) }}` macro call, so both branches below mask the same way.
  3. duckdb   = app.core.translate.translate(tokens)   (PLAN.md 5.4 rule table, ends with the
                as-of pinning current_date() -> {{ audit_today() }} etc.)
     databricks = app.core.translate.pin_time(tokens)  (ONLY that same pinning; otherwise the
                runner's text, verbatim -- the library's copy-paste promise)
  4. both branches: `system.<s>.<t>` -> `{{ source('system_<s>', '<t>') }}` outside literals and
                comments, validated against dbt/models/sources/sources.yml; the pairs found must
                equal the header's `reads:` (header/body drift is an error, never silent).
  5. both branches: `__W__` -> `{{ w }}`, `__P__x__` -> `{{ param('<qid>', 'x', <default>) }}`.
  6. model text: one `SELECT {{ w }} AS window_days, q.* FROM (...) q` block per window joined by
                UNION ALL (windowed queries), or one `SELECT 0 AS window_days ...` block (no loop).

Outputs (LF, byte-identical on rerun, no timestamps):
  dbt/models/findings/<domain>/f_<query_id>.sql
  dbt/models/findings/<domain>/_findings__<domain>.yml    (all models present in that domain)
  dbt/models/findings/generated_manifest.json             (models written, skipped + reason, lock commit)

DEC-13: the three DRILLDOWN_IDS get the extra dbt tag `drilldown` (an explicit allowlist).
DEC-24: config/grains/*.yml list a query's own key columns; `window_days` is prepended here.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.core.registry import QuerySpec, load_registry  # noqa: E402
from app.core.translate import (  # noqa: E402
    Untranslatable, mask, mask_user_identities, pin_time, strip_comments, strip_resource_mask,
    translate,
)

FINDINGS_DIR = ROOT / "dbt" / "models" / "findings"
MANIFEST_NAME = "generated_manifest.json"
LOCK_PATH = ROOT / "config" / "vendored.lock"
GRAINS_DIR = ROOT / "config" / "grains"
SOURCES_YML = ROOT / "dbt" / "models" / "sources" / "sources.yml"

# DEC-13: the P1 gate's `--select tag:drilldown` resolves to exactly these three models.
DRILLDOWN_IDS = (
    "lakeflow_long_running_runs",
    "task_cluster_utilization",
    "query_task_statement_breakdown",
)
WINDOWS = [7, 30, 90]
WINDOW_VALUES = [0, 7, 30, 90]
STATUS_VALUES = ["OK", "WARN", "CRITICAL", "NOT_ASSESSED"]
GENERATED_MARK = "GENERATED by tools/generate_models.py"


class GenerationError(ValueError):
    """A body the generator refuses (Jinja delimiter, unknown :param, header/body drift, a
    source outside sources.yml, a hand-written file in the way). Never swallowed."""


# ---------------------------------------------------------------------------------------------
# body preparation
# ---------------------------------------------------------------------------------------------

_JINJA_DELIMS = ("{{", "}}", "{%", "%}", "{#", "#}")
_STARTS_RE = re.compile(r"^\s*(SELECT|WITH)\b", re.IGNORECASE)
_WINDOW_DAYS_RE = re.compile(r"\bwindow_days\b", re.IGNORECASE)
_PARAM_LEFTOVER_RE = re.compile(r"(?<![:\w]):([a-z_][a-z0-9_]*)\b")


def runner_body(body: str) -> str:
    """The public runner's own body: every line starting with `--` dropped (the header, and any
    column-0 comment line inside the body), stripped, trailing `;` removed."""
    text = "\n".join(line for line in body.splitlines() if not line.startswith("--"))
    return text.strip().rstrip(";").rstrip()


def guard_body(query_id: str, body: str) -> None:
    if not _STARTS_RE.match(body):
        raise GenerationError(f"{query_id}: body does not start with SELECT/WITH")
    for d in _JINJA_DELIMS:
        if d in body:
            raise GenerationError(
                f"{query_id}: body contains the Jinja delimiter {d!r}; it cannot be emitted as a "
                "dbt model without escaping"
            )
    if _WINDOW_DAYS_RE.search(mask(body)):
        raise GenerationError(f"{query_id}: body already names a column window_days")


# The settings query_source tag, filled by dbt (var) locally and by the export at run time.
QUERY_SOURCE_MARKER = "__QUERY_SOURCE__"
QUERY_SOURCE_DEFAULT = "Crosshire"


def tokenise_params(query_id: str, body: str, params: list[dict]) -> str:
    """`:period_days` -> `__W__`, other known `:name` -> `__P__name__` (longest name first, the
    runner's alternation, substituted everywhere exactly as resolve_sql() does). Any `:name` still
    present outside a literal/comment afterwards is an unknown param -> GenerationError."""
    known = sorted({p["name"] for p in params}, key=len, reverse=True)
    if known:
        pat = re.compile(r":(" + "|".join(re.escape(k) for k in known) + r")\b")
        body = pat.sub(
            lambda m: "__W__" if m.group(1) == "period_days" else f"__P__{m.group(1)}__", body
        )
    left = sorted({m.group(1) for m in _PARAM_LEFTOVER_RE.finditer(mask(body))})
    if left:
        raise GenerationError(
            f"{query_id}: unknown :param token(s) {left} -- not declared in the header's params"
        )
    return body.replace(QUERY_SOURCE_MARKER, f"{{{{ var('query_source', '{QUERY_SOURCE_DEFAULT}') }}}}")


_SOURCE_RE = re.compile(r"(?<![\w.`])system\.([a-z_][a-z0-9_]*)\.([a-z_][a-z0-9_]*)\b")

# These ids need the raw, non-deduplicated list_prices join (cost_chargeback_reconcile's
# price_join_fanout check compares it against a de-duplicated total; the *_raw ids collect the
# table as-is) -- every other reader gets {{ list_prices() }} instead of a plain source() call.
RAW_LIST_PRICES_IDS = frozenset({
    "cost_chargeback_reconcile",
    "overview_list_prices_raw",
    "pricing_list_prices_raw",
    "cost_account_prices_raw",
})

_ALIAS_STOP_WORDS = frozenset({
    "where", "group", "order", "union", "left", "right", "inner", "full", "cross",
    "join", "having", "limit", "qualify", "on",
})


def _needs_list_prices_alias(rest: str) -> bool:
    """After a bare `system.billing.list_prices` reference: true when no alias follows it directly
    (a line break, ')', ',' or a keyword), so the {{ list_prices() }} subquery that replaces it
    needs its own alias to stay valid SQL on both engines."""
    stripped = rest.lstrip(" \t")
    if stripped[:1] in ("", ")", ",", "\n"):
        return True
    word = re.match(r"[A-Za-z_][A-Za-z0-9_]*", stripped)
    return not word or word.group(0).lower() in _ALIAS_STOP_WORDS


def load_source_contract(sources_yml: Path = SOURCES_YML) -> dict[str, set[str]]:
    """{schema: {table, ...}} from dbt/models/sources/sources.yml (source name `system_<schema>`)."""
    doc = yaml.safe_load(sources_yml.read_text(encoding="utf-8"))
    contract: dict[str, set[str]] = {}
    for src in doc.get("sources", []):
        name = src["name"]
        schema = src.get("schema") or name.removeprefix("system_")
        if name != f"system_{schema}":
            raise GenerationError(f"sources.yml: source {name!r} does not follow system_<schema>")
        contract[schema] = {t["name"] for t in src.get("tables", [])}
    return contract


def substitute_sources(
    query_id: str, body: str, contract: dict[str, set[str]]
) -> tuple[str, list[tuple[str, str]]]:
    """`system.<s>.<t>` -> `{{ source('system_<s>', '<t>') }}` outside literals and comments.
    Returns the rewritten text and the (schema, table) pairs found, in order of first use."""
    m_text = mask(body)
    out: list[str] = []
    last = 0
    pairs: list[tuple[str, str]] = []
    for m in _SOURCE_RE.finditer(m_text):
        schema, table = m.group(1), m.group(2)
        if schema not in contract:
            raise GenerationError(f"{query_id}: system.{schema}.{table} -- schema not in sources.yml")
        if table not in contract[schema]:
            raise GenerationError(
                f"{query_id}: system.{schema}.{table} -- table not in sources.yml under system_{schema}"
            )
        if (schema, table) not in pairs:
            pairs.append((schema, table))
        out.append(body[last:m.start()])
        if (schema, table) == ("billing", "list_prices") and query_id not in RAW_LIST_PRICES_IDS:
            call = "{{ list_prices() }}"
            if _needs_list_prices_alias(body[m.end():]):
                call += " list_prices"
            out.append(call)
        else:
            out.append(f"{{{{ source('system_{schema}', '{table}') }}}}")
        last = m.end()
    out.append(body[last:])
    return "".join(out), pairs


def reads_drift(spec: QuerySpec) -> tuple[list[str], list[str]]:
    """(header_only, body_only): `system.<s>.<t>` pairs the header's `reads:` names but the body
    never reads, and pairs the body reads but the header omits. Both empty = no drift."""
    m_text = mask(runner_body(spec.body))
    found = {(m.group(1), m.group(2)) for m in _SOURCE_RE.finditer(m_text)}
    header = {tuple(p) for p in spec.sources}
    fmt = lambda pairs: sorted(f"system.{s}.{t}" for s, t in pairs)  # noqa: E731
    return fmt(header - found), fmt(found - header)


_W_RE = re.compile(r"\b__W__\b")
_P_RE = re.compile(r"\b__P__(\w+?)__(?!\w)")


def _literal(value) -> str:
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def expand_sentinels(query_id: str, text: str, params: list[dict]) -> str:
    defaults = {p["name"]: p["default"] for p in params}

    def rep(m: re.Match) -> str:
        name = m.group(1)
        if name not in defaults:
            raise GenerationError(f"{query_id}: sentinel __P__{name}__ has no header default")
        return f"{{{{ param('{query_id}', '{name}', {_literal(defaults[name])}) }}}}"

    text = _W_RE.sub("{{ w }}", text)
    return _P_RE.sub(rep, text)


# ---------------------------------------------------------------------------------------------
# meta extraction (order_by, limit)
# ---------------------------------------------------------------------------------------------

_ORDER_BY_RE = re.compile(r"\bORDER\s+BY\b", re.IGNORECASE)
_LIMIT_RE = re.compile(r"\bLIMIT\b", re.IGNORECASE)


def _depth_at(m_text: str) -> list[int]:
    """Parenthesis depth before each character of a masked string."""
    depths = []
    d = 0
    for ch in m_text:
        depths.append(d)
        if ch == "(":
            d += 1
        elif ch == ")":
            d -= 1
    return depths


def _top_level_tail(body: str, keyword: re.Pattern) -> tuple[int, int] | None:
    """(start, end) of the text after the LAST depth-0 occurrence of `keyword`, up to the next
    depth-0 LIMIT (when keyword is ORDER BY) or the end of the body."""
    m_text = mask(body)
    depths = _depth_at(m_text)
    hits = [m for m in keyword.finditer(m_text) if depths[m.start()] == 0]
    if not hits:
        return None
    start = hits[-1].end()
    end = len(body)
    if keyword is _ORDER_BY_RE:
        for m in _LIMIT_RE.finditer(m_text, start):
            if depths[m.start()] == 0:
                end = m.start()
                break
    return start, end


def _clean_clause(text: str) -> str:
    return " ".join(strip_comments(text).split())


def extract_order_by(body: str) -> str:
    """The text after the body's final top-level ORDER BY (the subaudit build_sql.py recipe,
    made parenthesis-aware), comments removed, whitespace collapsed; "" when there is none."""
    span = _top_level_tail(body, _ORDER_BY_RE)
    if span is None:
        return ""
    return _clean_clause(body[span[0]:span[1]])


def extract_limit(body: str) -> str:
    """The text after the body's final top-level LIMIT; "" when there is none."""
    span = _top_level_tail(body, _LIMIT_RE)
    if span is None:
        return ""
    return _clean_clause(body[span[0]:span[1]])


# ---------------------------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------------------------


def skip_reason(spec: QuerySpec) -> str | None:
    if spec.executable:
        return None
    if not spec.runnable:
        return "runnable: false (a DESCRIBE/ANALYZE template, not a SELECT)"
    return "reads no system table (" + (spec.reads[0] if spec.reads else "reads empty") + ")"


def model_name(spec: QuerySpec) -> str:
    return f"f_{spec.query_id}"


def model_tags(spec: QuerySpec) -> list[str]:
    tags = ["finding" if spec.is_finding else "inventory", f"domain:{spec.domain}", f"tier:{spec.tier}"]
    if spec.stars:
        tags.append("stars")
    if spec.query_id in DRILLDOWN_IDS:
        tags.append("drilldown")
    return tags


def render_branches(spec: QuerySpec, contract: dict[str, set[str]] | None = None) -> dict[str, str]:
    """{'duckdb': ..., 'databricks': ...}: the two derived-table bodies, fully substituted."""
    if not spec.executable:
        raise GenerationError(f"{spec.query_id}: not executable ({skip_reason(spec)})")
    contract = contract if contract is not None else load_source_contract()
    body = runner_body(spec.body)
    guard_body(spec.query_id, body)
    tokens = tokenise_params(spec.query_id, body, spec.params)
    # A resource-name preview -> the plain column, an identity mask -> the mask_user() macro call
    # -- before translate()/pin_time() so both branches get the identical rewrite.
    tokens = strip_resource_mask(tokens)
    tokens = mask_user_identities(tokens)
    try:
        duck = translate(tokens)
    except Untranslatable as e:
        raise GenerationError(f"{spec.query_id}: {e}") from e
    dbx = pin_time(tokens)
    duck, _ = substitute_sources(spec.query_id, duck, contract)
    dbx, pairs = substitute_sources(spec.query_id, dbx, contract)
    header_only, body_only = reads_drift(spec)
    if header_only or body_only:
        raise GenerationError(
            f"{spec.query_id}: header/body drift -- reads: names {header_only} the body never "
            f"reads; the body reads {body_only} the header omits"
        )
    return {
        "duckdb": expand_sentinels(spec.query_id, duck, spec.params),
        "databricks": expand_sentinels(spec.query_id, dbx, spec.params),
    }


def _origin_note(spec: QuerySpec, lock_commit: str) -> str:
    if spec.origin == "vendored":
        return f"{spec.path} (vendored @ {lock_commit})"
    return f"{spec.path} (app-owned)"


def render_model(
    spec: QuerySpec,
    target: str = "both",
    *,
    lock_commit: str | None = None,
    contract: dict[str, set[str]] | None = None,
) -> str:
    """The dbt model text (PLAN.md 5.3). target='both' emits the `{% if target.type == 'duckdb' %}`
    dual-branch model the CLI writes; 'duckdb' / 'databricks' emit a single-branch variant of the
    same shape (for tests that inspect one dialect without a Jinja render)."""
    if target not in ("both", "duckdb", "databricks"):
        raise ValueError(f"target must be both|duckdb|databricks, got {target!r}")
    branches = render_branches(spec, contract)
    commit = lock_commit if lock_commit is not None else load_lock_commit()
    tags = ", ".join(f"'{t}'" for t in model_tags(spec))
    if target == "both":
        inner = (
            "{%- if target.type == 'duckdb' %}\n"
            + branches["duckdb"]
            + "\n{%- else %}\n"
            + branches["databricks"]
            + "\n{%- endif %}"
        )
    else:
        inner = branches[target]
    head = (
        f"{{{{ config(materialized='table', tags=[{tags}]) }}}}\n"
        f"-- {GENERATED_MARK} from {_origin_note(spec, commit)}. Do not edit.\n"
    )
    if spec.windowed:
        return (
            head
            + "{%- set windows = var('windows', [7, 30, 90]) %}\n"
            "{%- for w in windows %}\n"
            "SELECT {{ w }} AS window_days, q.*\n"
            "FROM (\n"
            + inner
            + "\n) q\n"
            "{%- if not loop.last %}\n"
            "UNION ALL\n"
            "{%- endif %}\n"
            "{%- endfor %}\n"
        )
    return head + "SELECT 0 AS window_days, q.*\nFROM (\n" + inner + "\n) q\n"


def load_grains(grains_dir: Path = GRAINS_DIR) -> dict[str, list[str]]:
    """{query_id: [own key columns]} from every config/grains/*.yml (each file is a mapping
    query_id -> list of column names). An id named in two files is an error."""
    grains: dict[str, list[str]] = {}
    owner: dict[str, str] = {}
    if not grains_dir.exists():
        return grains
    for path in sorted(grains_dir.glob("*.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(doc, dict):
            raise GenerationError(f"{path}: expected a mapping query_id -> [columns]")
        for qid, cols in doc.items():
            if isinstance(cols, dict):
                cols = cols.get("columns")
            if not isinstance(cols, list) or not cols or not all(isinstance(c, str) for c in cols):
                raise GenerationError(f"{path}: grain for {qid!r} must be a non-empty list of column names")
            if "window_days" in cols:
                raise GenerationError(f"{path}: grain for {qid!r} must not list window_days (DEC-24)")
            if qid in grains:
                raise GenerationError(f"grain for {qid!r} is defined in both {owner[qid]} and {path.name}")
            grains[qid] = list(cols)
            owner[qid] = path.name
    return grains


def load_lock_commit(lock_path: Path = LOCK_PATH) -> str:
    return str(json.loads(lock_path.read_text(encoding="utf-8"))["commit"])


def _limit_note(spec: QuerySpec, body: str) -> str:
    limit = extract_limit(body)
    if not limit:
        return ""
    defaults = {p["name"]: p["default"] for p in spec.params}
    m = re.fullmatch(r":([a-z_][a-z0-9_]*)", limit)
    if m and m.group(1) in defaults:
        return (f" Rows are capped inside every window_days block by the body's LIMIT :{m.group(1)}"
                f" (default {_literal(defaults[m.group(1)])}, threshold '{m.group(1)}').")
    return f" Rows are capped inside every window_days block by the body's LIMIT {limit}."


def model_entry(spec: QuerySpec, grains: dict[str, list[str]]) -> dict:
    body = runner_body(spec.body)
    entry: dict = {
        "name": model_name(spec),
        "description": spec.read_this + _limit_note(spec, body),
        "meta": {
            "query_id": spec.query_id,
            "title": spec.title,
            "domain": spec.domain,
            "tier": spec.tier,
            "stars": spec.stars,
            "origin": spec.origin,
            "windowed": spec.windowed,
            "is_finding": spec.is_finding,
            "empty_if": list(spec.empty_if),
            "reads": list(spec.reads),
            "requires": spec.requires,
            "params": [dict(p) for p in spec.params],
            "confidence": spec.confidence,
            "confidence_note": spec.confidence_note,
            "healthy": spec.healthy,
            "investigate_if": spec.investigate_if,
            "actions": list(spec.actions),
            "next": [dict(n) for n in spec.next],
            "caveats": spec.caveats,
            "sql_url": spec.sql_url,
            "order_by": extract_order_by(body),
        },
    }
    columns = [
        {
            "name": "window_days",
            "data_tests": [
                "not_null",
                {"accepted_values": {"arguments": {"values": list(WINDOW_VALUES), "quote": False}}},
            ],
        }
    ]
    if spec.is_finding:
        columns.append(
            {
                "name": "status",
                "data_tests": [{"accepted_values": {"arguments": {"values": list(STATUS_VALUES)}}}],
            }
        )
    entry["columns"] = columns
    if spec.query_id in grains:
        entry["data_tests"] = [
            {"unique_grain": {"arguments": {"columns": ["window_days"] + grains[spec.query_id]}}}
        ]
    return entry


def render_domain_yml(domain: str, specs: list[QuerySpec], *, grains: dict[str, list[str]] | None = None) -> str:
    """The per-domain schema file `_findings__<domain>.yml` for every model in `specs`."""
    grains = grains if grains is not None else load_grains()
    ordered = sorted((s for s in specs if s.domain == domain), key=lambda s: s.query_id)
    doc = {"version": 2, "models": [model_entry(s, grains) for s in ordered]}
    text = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100, allow_unicode=False)
    return (
        f"# {GENERATED_MARK} for domain '{domain}'. Do not edit; rerun the generator.\n" + text
    )


# ---------------------------------------------------------------------------------------------
# files, manifest, check
# ---------------------------------------------------------------------------------------------


def model_path(spec: QuerySpec, out_dir: Path) -> Path:
    return out_dir / spec.domain / f"{model_name(spec)}.sql"


def yml_path(domain: str, out_dir: Path) -> Path:
    return out_dir / domain / f"_findings__{domain}.yml"


def _rel(path: Path, out_dir: Path = FINDINGS_DIR) -> str:
    """Repo-relative when under the repo (the real run); relative to the output directory
    otherwise (tests generate into a temporary directory), so no absolute path is ever baked in."""
    for base in (ROOT, out_dir):
        try:
            return path.relative_to(base).as_posix()
        except ValueError:
            continue
    return path.as_posix()


def load_manifest(out_dir: Path) -> dict:
    path = out_dir / MANIFEST_NAME
    if not path.exists():
        return {"commit": None, "models": [], "skipped": [], "ymls": []}
    return json.loads(path.read_text(encoding="utf-8"))


def _manifest_model(spec: QuerySpec, out_dir: Path) -> dict:
    return {
        "query_id": spec.query_id,
        "domain": spec.domain,
        "model": model_name(spec),
        "path": _rel(model_path(spec, out_dir), out_dir),
        "origin": spec.origin,
        "windowed": spec.windowed,
        "is_finding": spec.is_finding,
        "tags": model_tags(spec),
    }


def build_manifest(
    existing: dict, scope: list[QuerySpec], registry: dict[str, QuerySpec], out_dir: Path, commit: str
) -> dict:
    """The manifest after this run: entries for ids outside `scope` are kept (re-described from
    the registry when the id still exists), entries for ids in scope are recomputed."""
    scope_ids = {s.query_id for s in scope}
    models: dict[str, dict] = {}
    skipped: dict[str, dict] = {}
    for m in existing.get("models", []):
        qid = m["query_id"]
        if qid in scope_ids or qid not in registry:
            continue
        spec = registry[qid]
        if spec.executable:
            models[qid] = _manifest_model(spec, out_dir)
    for s in existing.get("skipped", []):
        qid = s["query_id"]
        if qid in scope_ids or qid not in registry or qid in models:
            continue
        reason = skip_reason(registry[qid])
        if reason:
            skipped[qid] = {"query_id": qid, "domain": registry[qid].domain, "reason": reason}
    for spec in scope:
        reason = skip_reason(spec)
        if reason:
            skipped[spec.query_id] = {"query_id": spec.query_id, "domain": spec.domain, "reason": reason}
        else:
            models[spec.query_id] = _manifest_model(spec, out_dir)
    domains = sorted({m["domain"] for m in models.values()})
    return {
        "commit": commit,
        "models": [models[k] for k in sorted(models)],
        "skipped": [skipped[k] for k in sorted(skipped)],
        "ymls": [_rel(yml_path(d, out_dir), out_dir) for d in domains],
    }


def manifest_text(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def _write(path: Path, text: str, force: bool) -> None:
    if path.exists() and not force:
        head = path.read_text(encoding="utf-8")[:400]
        if GENERATED_MARK not in head:
            raise GenerationError(
                f"{_rel(path)} exists and lacks the '{GENERATED_MARK}' marker; refusing to "
                "overwrite a hand-written file (use --force)"
            )
    path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes() == data and not force:
        return
    path.write_bytes(data)


def select_scope(registry: dict[str, QuerySpec], only: list[str] | None, domain: str | None) -> list[QuerySpec]:
    if only:
        unknown = [q for q in only if q not in registry]
        if unknown:
            raise GenerationError(f"unknown query id(s): {unknown}")
        return [registry[q] for q in only]
    if domain:
        specs = [s for s in registry.values() if s.domain == domain]
        if not specs:
            raise GenerationError(f"no query has domain {domain!r}")
        return specs
    return list(registry.values())


def _expected_files(
    manifest: dict, registry: dict[str, QuerySpec], out_dir: Path, commit: str,
    contract: dict[str, set[str]], grains: dict[str, list[str]],
) -> dict[Path, str]:
    """Every file the manifest implies, rendered: model files, domain ymls, the manifest."""
    expected: dict[Path, str] = {}
    by_domain: dict[str, list[QuerySpec]] = {}
    for m in manifest["models"]:
        spec = registry[m["query_id"]]
        expected[model_path(spec, out_dir)] = render_model(spec, lock_commit=commit, contract=contract)
        by_domain.setdefault(spec.domain, []).append(spec)
    for domain, specs in by_domain.items():
        expected[yml_path(domain, out_dir)] = render_domain_yml(domain, specs, grains=grains)
    expected[out_dir / MANIFEST_NAME] = manifest_text(manifest)
    return expected


def generate(
    only: list[str] | None = None,
    domain: str | None = None,
    *,
    force: bool = False,
    out_dir: Path = FINDINGS_DIR,
    grains_dir: Path = GRAINS_DIR,
    lock_path: Path = LOCK_PATH,
    sources_yml: Path = SOURCES_YML,
    registry: list[QuerySpec] | None = None,
) -> dict:
    """Render and write the models in scope, their domain ymls and the manifest. Returns
    {'models': [...ids written], 'skipped': [{query_id, reason}], 'ymls': [paths]}."""
    specs = registry if registry is not None else load_registry()
    reg = {s.query_id: s for s in specs}
    scope = select_scope(reg, only, domain)
    commit = load_lock_commit(lock_path)
    contract = load_source_contract(sources_yml)
    grains = load_grains(grains_dir)
    manifest = build_manifest(load_manifest(out_dir), scope, reg, out_dir, commit)
    written: list[str] = []
    touched_domains: set[str] = set()
    for spec in scope:
        if skip_reason(spec):
            continue
        _write(model_path(spec, out_dir), render_model(spec, lock_commit=commit, contract=contract), force)
        written.append(spec.query_id)
        touched_domains.add(spec.domain)
    for dom in sorted(touched_domains):
        dom_specs = [reg[m["query_id"]] for m in manifest["models"] if m["domain"] == dom]
        _write(yml_path(dom, out_dir), render_domain_yml(dom, dom_specs, grains=grains), force)
    _write(out_dir / MANIFEST_NAME, manifest_text(manifest), True)
    skipped_in_scope = [
        {"query_id": s.query_id, "reason": skip_reason(s)} for s in scope if skip_reason(s)
    ]
    return {
        "models": written,
        "skipped": skipped_in_scope,
        "ymls": [_rel(yml_path(d, out_dir), out_dir) for d in sorted(touched_domains)],
    }


def check(
    only: list[str] | None = None,
    domain: str | None = None,
    *,
    out_dir: Path = FINDINGS_DIR,
    grains_dir: Path = GRAINS_DIR,
    lock_path: Path = LOCK_PATH,
    sources_yml: Path = SOURCES_YML,
    registry: list[QuerySpec] | None = None,
) -> dict:
    """Compare what is on disk with what the generator would write. Returns
    {'ok': bool, 'stale': [...], 'missing': [...], 'extra': [...], 'models': n, 'skipped': [...]}.
    Unscoped: every model the manifest records (plus its ymls and the manifest itself) must be
    present and byte-identical, and no unrecorded .sql/.yml may sit under the findings dir.
    Scoped (--only/--domain): the same for the ids in scope and the ymls of their domains."""
    specs = registry if registry is not None else load_registry()
    reg = {s.query_id: s for s in specs}
    commit = load_lock_commit(lock_path)
    contract = load_source_contract(sources_yml)
    grains = load_grains(grains_dir)
    # the manifest on disk names WHICH ids were generated; every other field is re-derived from
    # the registry so a changed header (tags, is_finding, ...) shows up as a stale file
    manifest = build_manifest(load_manifest(out_dir), [], reg, out_dir, commit)
    manifest_ids = {m["query_id"] for m in manifest["models"]}

    stale: list[str] = []
    missing: list[str] = []
    extra: list[str] = []
    skipped: list[dict] = []
    expected: dict[Path, str] = {}

    if only or domain:
        scope = select_scope(reg, only, domain)
        scope_models = [s for s in scope if not skip_reason(s)]
        skipped = [{"query_id": s.query_id, "reason": skip_reason(s)} for s in scope if skip_reason(s)]
        for spec in scope_models:
            if spec.query_id not in manifest_ids:
                missing.append(_rel(model_path(spec, out_dir), out_dir) + " (never generated)")
            else:
                expected[model_path(spec, out_dir)] = render_model(spec, lock_commit=commit, contract=contract)
        # a domain yml must describe EVERY model recorded for that domain, not just the scope
        for dom in sorted({s.domain for s in scope_models}):
            dom_specs = [reg[m["query_id"]] for m in manifest["models"] if m["domain"] == dom]
            if dom_specs:
                expected[yml_path(dom, out_dir)] = render_domain_yml(dom, dom_specs, grains=grains)
        n_models = len(scope_models)
    else:
        expected = _expected_files(manifest, reg, out_dir, commit, contract, grains)
        skipped = [{"query_id": s["query_id"], "reason": s["reason"]} for s in manifest["skipped"]]
        n_models = len(manifest["models"])

    for path, text in expected.items():
        if not path.exists():
            missing.append(_rel(path, out_dir))
        elif path.read_bytes() != text.encode("utf-8"):
            stale.append(_rel(path, out_dir))

    known_paths = set()
    for m in manifest["models"]:
        known_paths.add(model_path(reg[m["query_id"]], out_dir))
    for dom in {m["domain"] for m in manifest["models"]}:
        known_paths.add(yml_path(dom, out_dir))
    if out_dir.exists():
        for path in sorted(out_dir.rglob("*")):
            if path.is_file() and path.suffix in (".sql", ".yml", ".yaml") and path not in known_paths:
                extra.append(_rel(path, out_dir))

    return {
        "ok": not (stale or missing or extra),
        "stale": stale,
        "missing": missing,
        "extra": extra,
        "models": n_models,
        "skipped": skipped,
    }


# ---------------------------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    scope = ap.add_mutually_exclusive_group()
    scope.add_argument("--only", nargs="+", metavar="ID", help="only these query ids")
    scope.add_argument("--domain", metavar="NAME", help="only this domain")
    ap.add_argument("--check", action="store_true", help="verify, do not write; exit 1 on any drift")
    ap.add_argument("--force", action="store_true", help="overwrite files lacking the GENERATED marker")
    args = ap.parse_args(argv)
    try:
        if args.check:
            r = check(args.only, args.domain)
            for s in r["skipped"]:
                print(f"skipped: {s['query_id']} - {s['reason']}")
            for p in r["stale"]:
                print(f"stale: {p}")
            for p in r["missing"]:
                print(f"missing: {p}")
            for p in r["extra"]:
                print(f"extra: {p}")
            if r["ok"]:
                print(f"models in sync ({r['models']} models, {len(r['skipped'])} skipped)")
                return 0
            print(
                f"models out of sync: {len(r['stale'])} stale, {len(r['missing'])} missing, "
                f"{len(r['extra'])} extra -- rerun python tools/generate_models.py",
                file=sys.stderr,
            )
            return 1
        r = generate(args.only, args.domain, force=args.force)
        for s in r["skipped"]:
            print(f"skipped: {s['query_id']} - {s['reason']}")
        n_y = len(r["ymls"])
        print(f"wrote {len(r['models'])} models, {n_y} yml{'s' if n_y != 1 else ''}, {MANIFEST_NAME}")
        return 0
    except GenerationError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
