{{ config(materialized='table', tags=['finding', 'domain:compute', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/compute/sql_warehouse_events_activity.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH current_warehouses AS (
  SELECT workspace_id, warehouse_id, warehouse_name, first_seen_time
  FROM (
    SELECT workspace_id, warehouse_id, warehouse_name, delete_time,
           MIN(change_time) OVER (PARTITION BY workspace_id, warehouse_id) AS first_seen_time,
           ROW_NUMBER() OVER (PARTITION BY workspace_id, warehouse_id ORDER BY change_time DESC) AS rn
    FROM {{ source('system_compute', 'warehouses') }}
  )
  WHERE rn = 1 AND delete_time IS NULL
),
events AS (
  SELECT workspace_id, warehouse_id, event_type,
         COUNT(*)           AS event_count,
         MAX(event_time)    AS last_event_time,
         MIN(event_time)    AS first_event_time,
         MAX(cluster_count) AS max_cluster_count,
         AVG(cluster_count) AS avg_cluster_count
  FROM {{ source('system_compute', 'warehouse_events') }}
  WHERE event_time >= {{ audit_now() }} - (({{ w }}) * INTERVAL 1 DAY)
  GROUP BY workspace_id, warehouse_id, event_type
),
warehouse_keys AS (
  -- current warehouses plus any warehouse with events, so a deleted/never-captured one still shows
  SELECT workspace_id, warehouse_id FROM current_warehouses
  UNION
  SELECT workspace_id, warehouse_id FROM events
),
running_events AS (
  SELECT workspace_id, warehouse_id, MAX(event_time) AS last_running_event_time
  FROM {{ source('system_compute', 'warehouse_events') }}
  WHERE event_type IN ('RUNNING', 'STARTING')
    AND event_time >= {{ audit_now() }} - (({{ w }}) * INTERVAL 1 DAY)
  GROUP BY workspace_id, warehouse_id
),
billed AS (
  SELECT workspace_id, usage_metadata.warehouse_id AS warehouse_id,
         SUM(usage_quantity) AS net_dbus
  FROM {{ source('system_billing', 'usage') }}
  WHERE upper(usage_unit) = 'DBU'
    AND usage_metadata.warehouse_id IS NOT NULL
    AND usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
    AND usage_date < {{ audit_today() }}
  GROUP BY workspace_id, usage_metadata.warehouse_id
)
SELECT wk.workspace_id, wk.warehouse_id, cw.warehouse_name,
       e.event_type,
       COALESCE(e.event_count, 0) AS event_count,
       e.last_event_time, e.first_event_time, e.max_cluster_count, e.avg_cluster_count,
       COALESCE(b.net_dbus, 0) AS net_dbus,
       CASE
         WHEN e.event_type IS NULL AND cw.first_seen_time >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
              THEN 'NOT_ASSESSED'                      -- first seen within the window: no activity expected yet
         WHEN e.event_type IS NULL AND COALESCE(b.net_dbus, 0) > 0
              THEN 'NOT_ASSESSED'                       -- billed with zero events: likely always-on, not confirmably dormant
         WHEN e.event_type IS NULL THEN 'CRITICAL'      -- zero events AND zero billed DBUs: genuinely dormant
         WHEN e.event_type NOT IN ('RUNNING', 'STARTING') THEN 'NOT_ASSESSED'
         WHEN (epoch({{ audit_now() }}) - epoch(re.last_running_event_time)) / 86400.0 >= {{ param('sql_warehouse_events_activity', 'crit_stale_days', 14) }} THEN 'CRITICAL'
         WHEN (epoch({{ audit_now() }}) - epoch(re.last_running_event_time)) / 86400.0 >= {{ param('sql_warehouse_events_activity', 'warn_stale_days', 7) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM warehouse_keys wk
LEFT JOIN current_warehouses cw ON wk.workspace_id = cw.workspace_id AND wk.warehouse_id = cw.warehouse_id
LEFT JOIN events e          ON wk.workspace_id = e.workspace_id AND wk.warehouse_id = e.warehouse_id
LEFT JOIN running_events re ON wk.workspace_id = re.workspace_id AND wk.warehouse_id = re.warehouse_id
LEFT JOIN billed b          ON wk.workspace_id = b.workspace_id AND wk.warehouse_id = b.warehouse_id
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'OK' THEN 2 ELSE 3 END,
         last_event_time ASC NULLS FIRST
{%- else %}
WITH current_warehouses AS (
  SELECT workspace_id, warehouse_id, warehouse_name, first_seen_time
  FROM (
    SELECT workspace_id, warehouse_id, warehouse_name, delete_time,
           MIN(change_time) OVER (PARTITION BY workspace_id, warehouse_id) AS first_seen_time,
           ROW_NUMBER() OVER (PARTITION BY workspace_id, warehouse_id ORDER BY change_time DESC) AS rn
    FROM {{ source('system_compute', 'warehouses') }}
  )
  WHERE rn = 1 AND delete_time IS NULL
),
events AS (
  SELECT workspace_id, warehouse_id, event_type,
         COUNT(*)           AS event_count,
         MAX(event_time)    AS last_event_time,
         MIN(event_time)    AS first_event_time,
         MAX(cluster_count) AS max_cluster_count,
         AVG(cluster_count) AS avg_cluster_count
  FROM {{ source('system_compute', 'warehouse_events') }}
  WHERE event_time >= {{ audit_now() }} - INTERVAL {{ w }} DAYS
  GROUP BY workspace_id, warehouse_id, event_type
),
warehouse_keys AS (
  -- current warehouses plus any warehouse with events, so a deleted/never-captured one still shows
  SELECT workspace_id, warehouse_id FROM current_warehouses
  UNION
  SELECT workspace_id, warehouse_id FROM events
),
running_events AS (
  SELECT workspace_id, warehouse_id, MAX(event_time) AS last_running_event_time
  FROM {{ source('system_compute', 'warehouse_events') }}
  WHERE event_type IN ('RUNNING', 'STARTING')
    AND event_time >= {{ audit_now() }} - INTERVAL {{ w }} DAYS
  GROUP BY workspace_id, warehouse_id
),
billed AS (
  SELECT workspace_id, usage_metadata.warehouse_id AS warehouse_id,
         SUM(usage_quantity) AS net_dbus
  FROM {{ source('system_billing', 'usage') }}
  WHERE upper(usage_unit) = 'DBU'
    AND usage_metadata.warehouse_id IS NOT NULL
    AND usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
    AND usage_date < {{ audit_today() }}
  GROUP BY workspace_id, usage_metadata.warehouse_id
)
SELECT wk.workspace_id, wk.warehouse_id, cw.warehouse_name,
       e.event_type,
       COALESCE(e.event_count, 0) AS event_count,
       e.last_event_time, e.first_event_time, e.max_cluster_count, e.avg_cluster_count,
       COALESCE(b.net_dbus, 0) AS net_dbus,
       CASE
         WHEN e.event_type IS NULL AND cw.first_seen_time >= dateadd(day, -{{ w }}, {{ audit_today() }})
              THEN 'NOT_ASSESSED'                      -- first seen within the window: no activity expected yet
         WHEN e.event_type IS NULL AND COALESCE(b.net_dbus, 0) > 0
              THEN 'NOT_ASSESSED'                       -- billed with zero events: likely always-on, not confirmably dormant
         WHEN e.event_type IS NULL THEN 'CRITICAL'      -- zero events AND zero billed DBUs: genuinely dormant
         WHEN e.event_type NOT IN ('RUNNING', 'STARTING') THEN 'NOT_ASSESSED'
         WHEN (unix_timestamp({{ audit_now() }}) - unix_timestamp(re.last_running_event_time)) / 86400.0 >= {{ param('sql_warehouse_events_activity', 'crit_stale_days', 14) }} THEN 'CRITICAL'
         WHEN (unix_timestamp({{ audit_now() }}) - unix_timestamp(re.last_running_event_time)) / 86400.0 >= {{ param('sql_warehouse_events_activity', 'warn_stale_days', 7) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM warehouse_keys wk
LEFT JOIN current_warehouses cw ON wk.workspace_id = cw.workspace_id AND wk.warehouse_id = cw.warehouse_id
LEFT JOIN events e          ON wk.workspace_id = e.workspace_id AND wk.warehouse_id = e.warehouse_id
LEFT JOIN running_events re ON wk.workspace_id = re.workspace_id AND wk.warehouse_id = re.warehouse_id
LEFT JOIN billed b          ON wk.workspace_id = b.workspace_id AND wk.warehouse_id = b.warehouse_id
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'OK' THEN 2 ELSE 3 END,
         last_event_time ASC NULLS FIRST
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
