{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_by_billing_origin_product.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT billing_origin_product, usage_unit, cloud, workspace_id,
       SUM(usage_quantity) AS net_usage_quantity,
       COUNT(*)            AS record_count
FROM {{ source('system_billing', 'usage') }}
WHERE usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND usage_date < {{ audit_today() }}
GROUP BY billing_origin_product, usage_unit, cloud, workspace_id
ORDER BY billing_origin_product, usage_unit, cloud, workspace_id
{%- else %}
SELECT billing_origin_product, usage_unit, cloud, workspace_id,
       SUM(usage_quantity) AS net_usage_quantity,
       COUNT(*)            AS record_count
FROM {{ source('system_billing', 'usage') }}
WHERE usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND usage_date < {{ audit_today() }}
GROUP BY billing_origin_product, usage_unit, cloud, workspace_id
ORDER BY billing_origin_product, usage_unit, cloud, workspace_id
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
