{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_account_prices_raw.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT price_start_time, price_end_time, account_id, sku_name, cloud, currency_code, usage_unit,
       CAST(pricing.default AS STRING) AS pricing_default
FROM {{ source('system_billing', 'list_prices') }}
ORDER BY sku_name, cloud, currency_code, price_start_time
{%- else %}
SELECT price_start_time, price_end_time, account_id, sku_name, cloud, currency_code, usage_unit,
       CAST(pricing.default AS STRING) AS pricing_default
FROM {{ source('system_billing', 'list_prices') }}
ORDER BY sku_name, cloud, currency_code, price_start_time
{%- endif %}
) q
