{{ config(materialized='table', tags=['finding', 'domain:cost', 'tier:deep']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_vector_search_spend.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT u.usage_date, u.cloud, u.workspace_id, u.sku_name, u.usage_type, u.usage_unit,
       u.usage_metadata.endpoint_name AS endpoint_name,
       u.usage_metadata.endpoint_id   AS endpoint_id,
       lp.currency_code,
       SUM(u.usage_quantity)                AS net_usage_quantity,
       SUM(u.usage_quantity * lp.list_rate) AS net_list_cost,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (NULL, understates cost).
       CASE
         WHEN lp.list_rate IS NOT NULL THEN 'priced'
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
         ELSE 'unpriced'
       END                                   AS price_basis,
       -- status: est_usd_list/day band per endpoint (field heuristic; {{ param('cost_vector_search_spend', 'warn_endpoint_usd_per_day', 25) }} / {{ param('cost_vector_search_spend', 'crit_endpoint_usd_per_day', 100) }}).
       -- a FREE_USAGE SKU with no matching price row is a real $0 (OK), never NOT_ASSESSED -- that
       -- reading is reserved for a genuine pricing-coverage gap (price_basis = 'unpriced').
       CASE
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' AND SUM(u.usage_quantity * lp.list_rate) IS NULL THEN 'OK'
         WHEN SUM(u.usage_quantity * lp.list_rate) IS NULL THEN 'NOT_ASSESSED'
         WHEN SUM(u.usage_quantity * lp.list_rate) >= {{ param('cost_vector_search_spend', 'crit_endpoint_usd_per_day', 100) }} THEN 'CRITICAL'
         WHEN SUM(u.usage_quantity * lp.list_rate) >= {{ param('cost_vector_search_spend', 'warn_endpoint_usd_per_day', 25) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, usage_unit, currency_code, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective (post-promotion) list price - DEC-66.1
  FROM {{ list_prices() }} list_prices
) lp
  ON u.sku_name = lp.sku_name
 AND u.cloud    = lp.cloud
 AND u.usage_unit = lp.usage_unit
 AND u.usage_end_time >= lp.price_start_time
 AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
WHERE u.billing_origin_product = 'VECTOR_SEARCH'
  AND u.usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND u.usage_date < {{ audit_today() }}
GROUP BY u.usage_date, u.cloud, u.workspace_id, u.sku_name, u.usage_type, u.usage_unit,
         u.usage_metadata.endpoint_name, u.usage_metadata.endpoint_id, lp.currency_code,
         CASE
           WHEN lp.list_rate IS NOT NULL THEN 'priced'
           WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
           ELSE 'unpriced'
         END
ORDER BY net_list_cost DESC NULLS LAST
{%- else %}
SELECT u.usage_date, u.cloud, u.workspace_id, u.sku_name, u.usage_type, u.usage_unit,
       u.usage_metadata.endpoint_name AS endpoint_name,
       u.usage_metadata.endpoint_id   AS endpoint_id,
       lp.currency_code,
       SUM(u.usage_quantity)                AS net_usage_quantity,
       SUM(u.usage_quantity * lp.list_rate) AS net_list_cost,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (NULL, understates cost).
       CASE
         WHEN lp.list_rate IS NOT NULL THEN 'priced'
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
         ELSE 'unpriced'
       END                                   AS price_basis,
       -- status: est_usd_list/day band per endpoint (field heuristic; {{ param('cost_vector_search_spend', 'warn_endpoint_usd_per_day', 25) }} / {{ param('cost_vector_search_spend', 'crit_endpoint_usd_per_day', 100) }}).
       -- a FREE_USAGE SKU with no matching price row is a real $0 (OK), never NOT_ASSESSED -- that
       -- reading is reserved for a genuine pricing-coverage gap (price_basis = 'unpriced').
       CASE
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' AND SUM(u.usage_quantity * lp.list_rate) IS NULL THEN 'OK'
         WHEN SUM(u.usage_quantity * lp.list_rate) IS NULL THEN 'NOT_ASSESSED'
         WHEN SUM(u.usage_quantity * lp.list_rate) >= {{ param('cost_vector_search_spend', 'crit_endpoint_usd_per_day', 100) }} THEN 'CRITICAL'
         WHEN SUM(u.usage_quantity * lp.list_rate) >= {{ param('cost_vector_search_spend', 'warn_endpoint_usd_per_day', 25) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, usage_unit, currency_code, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective (post-promotion) list price - DEC-66.1
  FROM {{ list_prices() }} list_prices
) lp
  ON u.sku_name = lp.sku_name
 AND u.cloud    = lp.cloud
 AND u.usage_unit = lp.usage_unit
 AND u.usage_end_time >= lp.price_start_time
 AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
WHERE u.billing_origin_product = 'VECTOR_SEARCH'
  AND u.usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND u.usage_date < {{ audit_today() }}
GROUP BY u.usage_date, u.cloud, u.workspace_id, u.sku_name, u.usage_type, u.usage_unit,
         u.usage_metadata.endpoint_name, u.usage_metadata.endpoint_id, lp.currency_code,
         CASE
           WHEN lp.list_rate IS NOT NULL THEN 'priced'
           WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
           ELSE 'unpriced'
         END
ORDER BY net_list_cost DESC NULLS LAST
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
