{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_workspace_names.sql (vendored @ f700dd5). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT workspace_id, workspace_name, status
FROM {{ source('system_access', 'workspaces_latest') }}
ORDER BY workspace_name, workspace_id
{%- else %}
SELECT workspace_id, workspace_name, status
FROM {{ source('system_access', 'workspaces_latest') }}
ORDER BY workspace_name, workspace_id
{%- endif %}
) q
