{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:deep', 'stars']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_dollarized_by_sku_day.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT u.workspace_id, u.usage_date, u.cloud, u.sku_name, u.billing_origin_product, u.usage_type, u.usage_unit,
       lp.currency_code,
       SUM(u.usage_quantity)               AS net_usage_quantity,
       SUM(u.usage_quantity * lp.list_rate) AS net_list_cost,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (NULL, understates cost).
       CASE
         WHEN lp.list_rate IS NOT NULL THEN 'priced'
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
         ELSE 'unpriced'
       END                                  AS price_basis
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, currency_code, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective (post-promotion) list price - DEC-66.1
  FROM {{ list_prices() }} list_prices
) lp
  ON u.sku_name   = lp.sku_name
 AND u.cloud      = lp.cloud
 AND u.usage_unit = lp.usage_unit
 AND u.usage_end_time >= lp.price_start_time
 AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
WHERE u.usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND u.usage_date < {{ audit_today() }}
GROUP BY u.workspace_id, u.usage_date, u.cloud, u.sku_name, u.billing_origin_product, u.usage_type, u.usage_unit, lp.currency_code,
         CASE
           WHEN lp.list_rate IS NOT NULL THEN 'priced'
           WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
           ELSE 'unpriced'
         END
ORDER BY u.usage_date DESC, u.cloud, u.sku_name
{%- else %}
SELECT u.workspace_id, u.usage_date, u.cloud, u.sku_name, u.billing_origin_product, u.usage_type, u.usage_unit,
       lp.currency_code,
       SUM(u.usage_quantity)               AS net_usage_quantity,
       SUM(u.usage_quantity * lp.list_rate) AS net_list_cost,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (NULL, understates cost).
       CASE
         WHEN lp.list_rate IS NOT NULL THEN 'priced'
         WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
         ELSE 'unpriced'
       END                                  AS price_basis
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, currency_code, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective (post-promotion) list price - DEC-66.1
  FROM {{ list_prices() }} list_prices
) lp
  ON u.sku_name   = lp.sku_name
 AND u.cloud      = lp.cloud
 AND u.usage_unit = lp.usage_unit
 AND u.usage_end_time >= lp.price_start_time
 AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
WHERE u.usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND u.usage_date < {{ audit_today() }}
GROUP BY u.workspace_id, u.usage_date, u.cloud, u.sku_name, u.billing_origin_product, u.usage_type, u.usage_unit, lp.currency_code,
         CASE
           WHEN lp.list_rate IS NOT NULL THEN 'priced'
           WHEN upper(u.sku_name) LIKE '%FREE_USAGE%' THEN 'free'
           ELSE 'unpriced'
         END
ORDER BY u.usage_date DESC, u.cloud, u.sku_name
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
