{{ config(materialized='table', tags=['finding', 'domain:cost', 'tier:standard']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/cost/cost_daily_spikes.sql (app-owned). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
WITH daily_sku AS (
  SELECT u.workspace_id, u.billing_origin_product, u.usage_date, u.sku_name,
         SUM(u.usage_quantity * lp.list_rate) AS sku_cost,
         SUM(u.usage_quantity)                AS sku_quantity,
         MAX(lp.list_rate)                    AS list_rate
  FROM {{ source('system_billing', 'usage') }} u
  LEFT JOIN (
    SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
           CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective list price, DEC-66.1
    FROM {{ list_prices() }} list_prices
  ) lp
    ON u.sku_name   = lp.sku_name
   AND u.cloud      = lp.cloud
   AND u.usage_unit = lp.usage_unit
   AND u.usage_end_time >= lp.price_start_time
   AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
  WHERE u.usage_date >= ({{ audit_today() }} - (({{ w }} + {{ param('cost_daily_spikes', 'baseline_days', 14) }})) * INTERVAL 1 DAY)
    AND u.usage_date <  {{ audit_today() }}
  GROUP BY u.workspace_id, u.billing_origin_product, u.usage_date, u.sku_name
),
daily AS (
  SELECT workspace_id, billing_origin_product, usage_date,
         SUM(sku_cost) AS day_cost,
         SUM(CASE WHEN list_rate IS NULL AND upper(sku_name) NOT LIKE '%FREE_USAGE%'
                  THEN sku_quantity ELSE 0 END)                          AS unpriced_quantity,
         SUM(CASE WHEN list_rate IS NOT NULL THEN sku_quantity ELSE 0 END) AS priced_quantity
  FROM daily_sku
  GROUP BY workspace_id, billing_origin_product, usage_date
),
candidates AS (
  SELECT * FROM daily WHERE usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
),
baseline_pairs AS (
  -- every earlier day, for the same workspace/product, that falls in this candidate day's own
  -- trailing {{ param('cost_daily_spikes', 'baseline_days', 14) }} window (never including the candidate day itself). Null-safe keys
  -- (IS NOT DISTINCT FROM) so account-level usage (workspace_id NULL, PLAN.md 5.7) finds its own
  -- account-level baseline instead of never matching (plain `=` never matches NULL = NULL).
  SELECT c.workspace_id, c.billing_origin_product, c.usage_date AS candidate_date,
         b.day_cost AS baseline_cost
  FROM candidates c
  JOIN daily b
    ON  b.workspace_id            IS NOT DISTINCT FROM c.workspace_id
    AND b.billing_origin_product  IS NOT DISTINCT FROM c.billing_origin_product
    AND b.usage_date >= (c.usage_date - ({{ param('cost_daily_spikes', 'baseline_days', 14) }}) * INTERVAL 1 DAY)
    AND b.usage_date <  c.usage_date
),
baseline AS (
  SELECT workspace_id, billing_origin_product, candidate_date,
         quantile_cont(baseline_cost, 0.5) AS baseline_median_cost,
         COUNT(*)                       AS baseline_days_seen
  FROM baseline_pairs
  GROUP BY workspace_id, billing_origin_product, candidate_date
),
ranked_sku AS (
  SELECT workspace_id, billing_origin_product, usage_date, sku_name, sku_cost
  FROM daily_sku
  WHERE usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY workspace_id, billing_origin_product, usage_date ORDER BY sku_cost DESC, sku_name
  ) <= 3
),
drivers AS (
  SELECT workspace_id, billing_origin_product, usage_date,
         array_to_string(list_distinct(list(CASE
             WHEN sku_cost IS NULL THEN concat(sku_name,
               CASE WHEN upper(sku_name) LIKE '%FREE_USAGE%' THEN ' (free)' ELSE ' (no list price)' END)
             ELSE concat(sku_name, ' ($', CAST(CAST(ROUND(sku_cost, 0) AS BIGINT) AS STRING), ')')
           END)), ', ') AS top_skus
  FROM ranked_sku
  GROUP BY workspace_id, billing_origin_product, usage_date
)
SELECT c.workspace_id,
       c.billing_origin_product,
       c.usage_date,
       ROUND(c.day_cost, 2)              AS est_day_usd_list,
       ROUND(bl.baseline_median_cost, 2) AS est_baseline_usd_list,
       COALESCE(bl.baseline_days_seen, 0) AS baseline_days_seen,
       ROUND(c.day_cost / NULLIF(bl.baseline_median_cost, 0), 2) AS spike_ratio_actual,
       d.top_skus AS top_skus,
       -- price_basis: a real $0 (free-usage SKUs) vs a pricing-coverage gap (understates the day).
       CASE
         WHEN c.unpriced_quantity > 0 THEN 'unpriced'
         WHEN c.priced_quantity = 0   THEN 'free'
         ELSE 'priced'
       END AS price_basis,
       -- the $ floor is checked FIRST (a day that can never clear it is not worth flagging at
       -- all, priced or not), then the baseline-size cases, then the ratio itself - see caveats.
       CASE
         WHEN COALESCE(c.day_cost, 0) < {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}                                  THEN 'OK'
         WHEN bl.baseline_days_seen IS NULL OR bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }} THEN 'NOT_ASSESSED'
         WHEN c.day_cost >= COALESCE(bl.baseline_median_cost, 0) * {{ param('cost_daily_spikes', 'spike_ratio', 2.0) }}          THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN COALESCE(c.day_cost, 0) < {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}                    THEN NULL
         WHEN bl.baseline_days_seen IS NULL OR bl.baseline_days_seen = 0  THEN 'no_baseline_history'
         WHEN bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }}                 THEN 'short_baseline'
         ELSE NULL
       END AS not_assessed_reason
FROM candidates c
LEFT JOIN baseline bl
  ON  bl.workspace_id           IS NOT DISTINCT FROM c.workspace_id
  AND bl.billing_origin_product IS NOT DISTINCT FROM c.billing_origin_product
  AND bl.candidate_date         = c.usage_date
LEFT JOIN drivers d
  ON  d.workspace_id           IS NOT DISTINCT FROM c.workspace_id
  AND d.billing_origin_product IS NOT DISTINCT FROM c.billing_origin_product
  AND d.usage_date             = c.usage_date
WHERE c.day_cost >= {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}
  AND (
        (bl.baseline_days_seen IS NULL OR bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }})
     OR c.day_cost >= COALESCE(bl.baseline_median_cost, 0) * {{ param('cost_daily_spikes', 'spike_ratio', 2.0) }}
      )
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'NOT_ASSESSED' THEN 2 ELSE 3 END,
         est_day_usd_list DESC,
         workspace_id, billing_origin_product, usage_date
{%- else %}
WITH daily_sku AS (
  SELECT u.workspace_id, u.billing_origin_product, u.usage_date, u.sku_name,
         SUM(u.usage_quantity * lp.list_rate) AS sku_cost,
         SUM(u.usage_quantity)                AS sku_quantity,
         MAX(lp.list_rate)                    AS list_rate
  FROM {{ source('system_billing', 'usage') }} u
  LEFT JOIN (
    SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
           CAST(pricing.effective_list.default AS DOUBLE) AS list_rate   -- effective list price, DEC-66.1
    FROM {{ list_prices() }} list_prices
  ) lp
    ON u.sku_name   = lp.sku_name
   AND u.cloud      = lp.cloud
   AND u.usage_unit = lp.usage_unit
   AND u.usage_end_time >= lp.price_start_time
   AND (lp.price_end_time IS NULL OR u.usage_end_time < lp.price_end_time)
  WHERE u.usage_date >= dateadd(day, -({{ w }} + {{ param('cost_daily_spikes', 'baseline_days', 14) }}), {{ audit_today() }})
    AND u.usage_date <  {{ audit_today() }}
  GROUP BY u.workspace_id, u.billing_origin_product, u.usage_date, u.sku_name
),
daily AS (
  SELECT workspace_id, billing_origin_product, usage_date,
         SUM(sku_cost) AS day_cost,
         SUM(CASE WHEN list_rate IS NULL AND upper(sku_name) NOT LIKE '%FREE_USAGE%'
                  THEN sku_quantity ELSE 0 END)                          AS unpriced_quantity,
         SUM(CASE WHEN list_rate IS NOT NULL THEN sku_quantity ELSE 0 END) AS priced_quantity
  FROM daily_sku
  GROUP BY workspace_id, billing_origin_product, usage_date
),
candidates AS (
  SELECT * FROM daily WHERE usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
),
baseline_pairs AS (
  -- every earlier day, for the same workspace/product, that falls in this candidate day's own
  -- trailing {{ param('cost_daily_spikes', 'baseline_days', 14) }} window (never including the candidate day itself). Null-safe keys
  -- (IS NOT DISTINCT FROM) so account-level usage (workspace_id NULL, PLAN.md 5.7) finds its own
  -- account-level baseline instead of never matching (plain `=` never matches NULL = NULL).
  SELECT c.workspace_id, c.billing_origin_product, c.usage_date AS candidate_date,
         b.day_cost AS baseline_cost
  FROM candidates c
  JOIN daily b
    ON  b.workspace_id            IS NOT DISTINCT FROM c.workspace_id
    AND b.billing_origin_product  IS NOT DISTINCT FROM c.billing_origin_product
    AND b.usage_date >= dateadd(day, -{{ param('cost_daily_spikes', 'baseline_days', 14) }}, c.usage_date)
    AND b.usage_date <  c.usage_date
),
baseline AS (
  SELECT workspace_id, billing_origin_product, candidate_date,
         percentile(baseline_cost, 0.5) AS baseline_median_cost,
         COUNT(*)                       AS baseline_days_seen
  FROM baseline_pairs
  GROUP BY workspace_id, billing_origin_product, candidate_date
),
ranked_sku AS (
  SELECT workspace_id, billing_origin_product, usage_date, sku_name, sku_cost
  FROM daily_sku
  WHERE usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY workspace_id, billing_origin_product, usage_date ORDER BY sku_cost DESC, sku_name
  ) <= 3
),
drivers AS (
  SELECT workspace_id, billing_origin_product, usage_date,
         array_join(collect_set(
           CASE
             WHEN sku_cost IS NULL THEN concat(sku_name,
               CASE WHEN upper(sku_name) LIKE '%FREE_USAGE%' THEN ' (free)' ELSE ' (no list price)' END)
             ELSE concat(sku_name, ' ($', CAST(CAST(ROUND(sku_cost, 0) AS BIGINT) AS STRING), ')')
           END
         ), ', ') AS top_skus
  FROM ranked_sku
  GROUP BY workspace_id, billing_origin_product, usage_date
)
SELECT c.workspace_id,
       c.billing_origin_product,
       c.usage_date,
       ROUND(c.day_cost, 2)              AS est_day_usd_list,
       ROUND(bl.baseline_median_cost, 2) AS est_baseline_usd_list,
       COALESCE(bl.baseline_days_seen, 0) AS baseline_days_seen,
       ROUND(c.day_cost / NULLIF(bl.baseline_median_cost, 0), 2) AS spike_ratio_actual,
       d.top_skus AS top_skus,
       -- price_basis: a real $0 (free-usage SKUs) vs a pricing-coverage gap (understates the day).
       CASE
         WHEN c.unpriced_quantity > 0 THEN 'unpriced'
         WHEN c.priced_quantity = 0   THEN 'free'
         ELSE 'priced'
       END AS price_basis,
       -- the $ floor is checked FIRST (a day that can never clear it is not worth flagging at
       -- all, priced or not), then the baseline-size cases, then the ratio itself - see caveats.
       CASE
         WHEN COALESCE(c.day_cost, 0) < {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}                                  THEN 'OK'
         WHEN bl.baseline_days_seen IS NULL OR bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }} THEN 'NOT_ASSESSED'
         WHEN c.day_cost >= COALESCE(bl.baseline_median_cost, 0) * {{ param('cost_daily_spikes', 'spike_ratio', 2.0) }}          THEN 'WARN'
         ELSE 'OK'
       END AS status,
       CASE
         WHEN COALESCE(c.day_cost, 0) < {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}                    THEN NULL
         WHEN bl.baseline_days_seen IS NULL OR bl.baseline_days_seen = 0  THEN 'no_baseline_history'
         WHEN bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }}                 THEN 'short_baseline'
         ELSE NULL
       END AS not_assessed_reason
FROM candidates c
LEFT JOIN baseline bl
  ON  bl.workspace_id           IS NOT DISTINCT FROM c.workspace_id
  AND bl.billing_origin_product IS NOT DISTINCT FROM c.billing_origin_product
  AND bl.candidate_date         = c.usage_date
LEFT JOIN drivers d
  ON  d.workspace_id           IS NOT DISTINCT FROM c.workspace_id
  AND d.billing_origin_product IS NOT DISTINCT FROM c.billing_origin_product
  AND d.usage_date             = c.usage_date
WHERE c.day_cost >= {{ param('cost_daily_spikes', 'min_spend_usd', 50) }}
  AND (
        (bl.baseline_days_seen IS NULL OR bl.baseline_days_seen < {{ param('cost_daily_spikes', 'min_baseline_days', 3) }})
     OR c.day_cost >= COALESCE(bl.baseline_median_cost, 0) * {{ param('cost_daily_spikes', 'spike_ratio', 2.0) }}
      )
ORDER BY CASE status WHEN 'CRITICAL' THEN 0 WHEN 'WARN' THEN 1 WHEN 'NOT_ASSESSED' THEN 2 ELSE 3 END,
         est_day_usd_list DESC,
         workspace_id, billing_origin_product, usage_date
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
