{{ config(materialized='table', tags=['finding', 'domain:cost', 'tier:standard', 'stars']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_by_job.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT u.usage_date, u.cloud, u.workspace_id, w.workspace_name, u.billing_origin_product,
       u.usage_metadata.job_id AS job_id,
       j.job_name,
       u.product_features.is_serverless AS is_serverless,
       SUM(u.usage_quantity) AS net_usage_quantity,
       ROUND(SUM(u.usage_quantity * COALESCE(p.list_rate, 0)), 2) AS usd_list,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (usd_list understates cost).
       CASE
         WHEN SUM(CASE WHEN p.list_rate IS NULL AND upper(u.sku_name) NOT LIKE '%FREE_USAGE%'
                       THEN u.usage_quantity ELSE 0 END) > 0 THEN 'unpriced'
         WHEN SUM(CASE WHEN p.list_rate IS NOT NULL THEN u.usage_quantity ELSE 0 END) = 0 THEN 'free'
         ELSE 'priced'
       END AS price_basis,
       COUNT(DISTINCT u.usage_metadata.job_run_id) AS distinct_runs,
       -- status: magnitude band on daily DBU cost per job (field heuristic; {{ param('cost_by_job', 'warn_job_dbus_per_day', 50) }} / {{ param('cost_by_job', 'crit_job_dbus_per_day', 200) }}) - size, not waste.
       CASE
         WHEN SUM(u.usage_quantity) IS NULL THEN 'NOT_ASSESSED'
         WHEN SUM(u.usage_quantity) >= {{ param('cost_by_job', 'crit_job_dbus_per_day', 200) }} THEN 'CRITICAL'
         WHEN SUM(u.usage_quantity) >= {{ param('cost_by_job', 'warn_job_dbus_per_day', 50) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate
  FROM {{ list_prices() }} list_prices
) p
  ON  u.sku_name = p.sku_name AND u.cloud = p.cloud AND u.usage_unit = p.usage_unit
  AND u.usage_end_time >= p.price_start_time
  AND (p.price_end_time IS NULL OR u.usage_end_time < p.price_end_time)
LEFT JOIN (
  SELECT workspace_id, job_id, name AS job_name
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
) j ON j.workspace_id = u.workspace_id AND j.job_id = u.usage_metadata.job_id
LEFT JOIN {{ source('system_access', 'workspaces_latest') }} w ON w.workspace_id = u.workspace_id
WHERE u.usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND u.usage_date < {{ audit_today() }}
  AND u.usage_unit = 'DBU'
  AND u.usage_metadata.job_id IS NOT NULL
GROUP BY u.usage_date, u.cloud, u.workspace_id, w.workspace_name, u.billing_origin_product,
         u.usage_metadata.job_id, j.job_name, u.product_features.is_serverless
ORDER BY net_usage_quantity DESC
{%- else %}
SELECT u.usage_date, u.cloud, u.workspace_id, w.workspace_name, u.billing_origin_product,
       u.usage_metadata.job_id AS job_id,
       j.job_name,
       u.product_features.is_serverless AS is_serverless,
       SUM(u.usage_quantity) AS net_usage_quantity,
       ROUND(SUM(u.usage_quantity * COALESCE(p.list_rate, 0)), 2) AS usd_list,
       -- price_basis: a real $0 (free-usage SKU) vs a pricing-coverage gap (usd_list understates cost).
       CASE
         WHEN SUM(CASE WHEN p.list_rate IS NULL AND upper(u.sku_name) NOT LIKE '%FREE_USAGE%'
                       THEN u.usage_quantity ELSE 0 END) > 0 THEN 'unpriced'
         WHEN SUM(CASE WHEN p.list_rate IS NOT NULL THEN u.usage_quantity ELSE 0 END) = 0 THEN 'free'
         ELSE 'priced'
       END AS price_basis,
       COUNT(DISTINCT u.usage_metadata.job_run_id) AS distinct_runs,
       -- status: magnitude band on daily DBU cost per job (field heuristic; {{ param('cost_by_job', 'warn_job_dbus_per_day', 50) }} / {{ param('cost_by_job', 'crit_job_dbus_per_day', 200) }}) - size, not waste.
       CASE
         WHEN SUM(u.usage_quantity) IS NULL THEN 'NOT_ASSESSED'
         WHEN SUM(u.usage_quantity) >= {{ param('cost_by_job', 'crit_job_dbus_per_day', 200) }} THEN 'CRITICAL'
         WHEN SUM(u.usage_quantity) >= {{ param('cost_by_job', 'warn_job_dbus_per_day', 50) }} THEN 'WARN'
         ELSE 'OK'
       END AS status
FROM {{ source('system_billing', 'usage') }} u
LEFT JOIN (
  SELECT sku_name, cloud, usage_unit, price_start_time, price_end_time,
         CAST(pricing.effective_list.default AS DOUBLE) AS list_rate
  FROM {{ list_prices() }} list_prices
) p
  ON  u.sku_name = p.sku_name AND u.cloud = p.cloud AND u.usage_unit = p.usage_unit
  AND u.usage_end_time >= p.price_start_time
  AND (p.price_end_time IS NULL OR u.usage_end_time < p.price_end_time)
LEFT JOIN (
  SELECT workspace_id, job_id, name AS job_name
  FROM {{ source('system_lakeflow', 'jobs') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY workspace_id, job_id ORDER BY change_time DESC) = 1
) j ON j.workspace_id = u.workspace_id AND j.job_id = u.usage_metadata.job_id
LEFT JOIN {{ source('system_access', 'workspaces_latest') }} w ON w.workspace_id = u.workspace_id
WHERE u.usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND u.usage_date < {{ audit_today() }}
  AND u.usage_unit = 'DBU'
  AND u.usage_metadata.job_id IS NOT NULL
GROUP BY u.usage_date, u.cloud, u.workspace_id, w.workspace_name, u.billing_origin_product,
         u.usage_metadata.job_id, j.job_name, u.product_features.is_serverless
ORDER BY net_usage_quantity DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
