{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:standard', 'stars']) }}
-- GENERATED by tools/generate_models.py from app/queries/vendored/cost/cost_chargeback_by_tag.sql (vendored @ f700dd5). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT usage_date, cloud, workspace_id, billing_origin_product, tag_key, tag_value,
       SUM(usage_quantity) AS net_usage_quantity,
       COUNT(*) AS record_count
FROM {{ source('system_billing', 'usage') }}
     LEFT JOIN LATERAL (SELECT e.key AS tag_key, e.value AS tag_value FROM unnest(map_entries(custom_tags)) AS x(e)) t ON TRUE
WHERE usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND usage_date < {{ audit_today() }}
GROUP BY usage_date, cloud, workspace_id, billing_origin_product, tag_key, tag_value
ORDER BY usage_date DESC, workspace_id, tag_key, tag_value
{%- else %}
SELECT usage_date, cloud, workspace_id, billing_origin_product, tag_key, tag_value,
       SUM(usage_quantity) AS net_usage_quantity,
       COUNT(*) AS record_count
FROM {{ source('system_billing', 'usage') }}
     LATERAL VIEW OUTER explode(custom_tags) t AS tag_key, tag_value
WHERE usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND usage_date < {{ audit_today() }}
GROUP BY usage_date, cloud, workspace_id, billing_origin_product, tag_key, tag_value
ORDER BY usage_date DESC, workspace_id, tag_key, tag_value
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
