{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/cost/overview_dbu_by_sku.sql (app-owned). Do not edit.
{%- set windows = var('windows', [7, 30, 90]) %}
{%- for w in windows %}
SELECT {{ w }} AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT
    workspace_id,
    sku_name,
    billing_origin_product,
    SUM(usage_quantity) AS net_dbus
FROM {{ source('system_billing', 'usage') }}
WHERE usage_unit = 'DBU'
  AND usage_date >= ({{ audit_today() }} - ({{ w }}) * INTERVAL 1 DAY)
  AND usage_date < {{ audit_today() }}
GROUP BY workspace_id, sku_name, billing_origin_product
ORDER BY net_dbus DESC
{%- else %}
SELECT
    workspace_id,
    sku_name,
    billing_origin_product,
    SUM(usage_quantity) AS net_dbus
FROM {{ source('system_billing', 'usage') }}
WHERE usage_unit = 'DBU'
  AND usage_date >= dateadd(day, -{{ w }}, {{ audit_today() }})
  AND usage_date < {{ audit_today() }}
GROUP BY workspace_id, sku_name, billing_origin_product
ORDER BY net_dbus DESC
{%- endif %}
) q
{%- if not loop.last %}
UNION ALL
{%- endif %}
{%- endfor %}
