{{ config(materialized='table', tags=['inventory', 'domain:cost', 'tier:lite']) }}
-- GENERATED by tools/generate_models.py from app/queries/app/cost/overview_list_prices_raw.sql (app-owned). Do not edit.
SELECT 0 AS window_days, q.*
FROM (
{%- if target.type == 'duckdb' %}
SELECT
    price_start_time,
    price_end_time,
    account_id,
    sku_name,
    cloud,
    currency_code,
    usage_unit,
    CAST(pricing.default AS STRING) AS pricing_default,
    CAST(pricing.effective_list AS STRING) AS pricing_effective_list_json,
    CAST(pricing.promotional AS STRING) AS pricing_promotional_json
FROM {{ source('system_billing', 'list_prices') }}
{%- else %}
SELECT
    price_start_time,
    price_end_time,
    account_id,
    sku_name,
    cloud,
    currency_code,
    usage_unit,
    CAST(pricing.default AS STRING) AS pricing_default,
    CAST(pricing.effective_list AS STRING) AS pricing_effective_list_json,
    CAST(pricing.promotional AS STRING) AS pricing_promotional_json
FROM {{ source('system_billing', 'list_prices') }}
{%- endif %}
) q
